In [1]:
%load_ext autoreload
%autoreload 2

from pathlib import Path
import random
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: "%.3g" % x))
import tensorflow as tf
import pandas as pd
from src import utils
from src.features.load_dataset import import_stamp_yoochoose
from scipy.sparse import csr_matrix
import matplotlib.pyplot as plt
from tqdm import tqdm
from collections import Counter
import os
import shutil
import datetime

from tensorflow import keras
from tqdm.notebook import tqdm
from collections import defaultdict
import functools
import copy
from itertools import chain
from src.models import TestModel
from src.models import stmp
from src.metrics import MrrMetric

physical_devices = tf.config.experimental.list_physical_devices('GPU')
print(f"tensorflow version: {tf.__version__}")

tensorflow version: 2.2.0


In [2]:
train_data, val_data, test_data, idx2item, embedding_sizes = import_stamp_yoochoose(64)

X_train, y_train = train_data
X_val, y_val = val_data
X_test, y_test = test_data

num_x_train = len(X_train)
n_items, max_session_len = embedding_sizes
max_embedding_key = n_items

print(f"n_items: {n_items}")
print(f"max_session_len: {max_session_len}")

using last item in session as class
using last item in session as class
train_val_test_split @ 0.8 train, 0.2 val, 0 test
n_items: 17695
max_session_len: 146


In [11]:
# config = TestModel.default_config(n_items, max_session_len)
# model = TestModel.model(config=config)

config = stmp.default_config(n_items)
model = stmp.model(config=config)

train_metrics = {
    "top10 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=10),
}
val_metrics = {
    "top10 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=10),
}
test_metrics = {
    "acc": tf.keras.metrics.SparseCategoricalAccuracy(),
    "top5 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=5),
    "top10 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=10),
    "top20 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=20),
    "mrr5": MrrMetric(k=5),
    "mrr10": MrrMetric(k=10),
    "mrr20": MrrMetric(k=20)
}

train_metrics_rec = defaultdict(lambda: [])
val_metrics_rec = defaultdict(lambda: [])
test_metrics_rec = defaultdict(lambda: [])

current_time = datetime.datetime.now().strftime("%Y-%m-%d_%H:%M:%S")
print(f"starting experiment '{current_time}'")
expr_dir = Path("logs")/current_time
train_log_dir = expr_dir/"train"
val_log_dir = expr_dir/"val"
test_log_dir = expr_dir/"test"

os.makedirs(expr_dir)
for tensorboard_dir in [train_log_dir, val_log_dir, test_log_dir]:
    os.makedirs(tensorboard_dir, exist_ok=True)

train_summary_writer = tf.summary.create_file_writer(str(train_log_dir))
val_summary_writer = tf.summary.create_file_writer(str(val_log_dir))
model_saver = utils.TopModelSaver("models/last_run_weights.h5py")

print(f"batch_size: {config['batch_size']}")
for epoch in range(config["epochs"]):
    print(f"epoch {epoch}")
    # Reset the metrics at the start of the next epoch
    for metric in utils.flatten([train_metrics.values(), val_metrics.values(), test_metrics.values()]):
        metric.reset_states()

    for i, (X, y) in tqdm(list(enumerate(utils.batchify(X_train, y_train, shuffle=True, batch_size=config["batch_size"])))):
        X = [sess[::-1] for sess in X] # reversing sessions so most recent item is last
        X, mask = utils.mask_length(X, maskoff_vals=config["maskoff"], maskon_vals=config["maskon"], justify="right")
        preds, loss = model.train_step(tf.constant(X), tf.constant(mask), tf.constant(y), train_metrics.values()) 
        if np.isnan(loss):
            print("LOSS IS NAN")
        with train_summary_writer.as_default():
            tf.summary.scalar('loss', loss.numpy(), step=epoch*(int(num_x_train/config["batch_size"])+1)+i)
            
    for X, y in tqdm(list(utils.batchify(X_val, y_val, shuffle=True, batch_size=config["batch_size"]))):
        X = [sess[::-1] for sess in X]
        X, mask = utils.mask_length(X, maskoff_vals=config["maskoff"], maskon_vals=config["maskon"], justify="right")
        preds = model.test_step(tf.constant(X), tf.constant(mask), tf.constant(y), val_metrics.values())
    with val_summary_writer.as_default():
        tf.summary.histogram("preds", preds, step=epoch) # intentionally only getting the last preds cause it takes a while

    with train_summary_writer.as_default():
        for label, metric in train_metrics.items():
            train_metrics_rec[label].append(metric.result())
            print(f"{label} train: {metric.result()}")
            tf.summary.scalar(label, metric.result(), step=epoch)
    with val_summary_writer.as_default():
        for label, metric in val_metrics.items():
            val_metrics_rec[label].append(metric.result())
            print(f"{label} val: {metric.result()}")
            tf.summary.scalar(label, metric.result(), step=epoch)

    model_saver.save_best(model, val_metrics["top10 acc"].result())

starting experiment '2020-07-07_16:44:21'
batch_size: 1024
epoch 0



top10 acc train: 0.10173007845878601
top10 acc val: 0.11157683283090591
new best score: 0.11157683283090591; saving weights @ models/last_run_weights.h5py
epoch 1



top10 acc train: 0.10196062177419662
top10 acc val: 0.08089529722929001
best score remains 0.11157683283090591; not saving weights
epoch 2



top10 acc train: 0.08252208679914474
top10 acc val: 0.08751781284809113
best score remains 0.11157683283090591; not saving weights
epoch 3



top10 acc train: 0.08731098473072052
top10 acc val: 0.08437421172857285
best score remains 0.11157683283090591; not saving weights
epoch 4



top10 acc train: 0.06933950632810593
top10 acc val: 0.057171598076820374
best score remains 0.11157683283090591; not saving weights
epoch 5



top10 acc train: 0.05241593345999718
top10 acc val: 0.04451337084174156
best score remains 0.11157683283090591; not saving weights
epoch 6



top10 acc train: 0.056638967245817184
top10 acc val: 0.05406991392374039
best score remains 0.11157683283090591; not saving weights
epoch 7



top10 acc train: 0.05108509957790375
top10 acc val: 0.06094391644001007
best score remains 0.11157683283090591; not saving weights
epoch 8



top10 acc train: 0.05678567290306091
top10 acc val: 0.05226758494973183
best score remains 0.11157683283090591; not saving weights
epoch 9



top10 acc train: 0.055915918201208115
top10 acc val: 0.056710537523031235
best score remains 0.11157683283090591; not saving weights
epoch 10



top10 acc train: 0.055674899369478226
top10 acc val: 0.054530974477529526
best score remains 0.11157683283090591; not saving weights
epoch 11



top10 acc train: 0.051441386342048645
top10 acc val: 0.05075865611433983
best score remains 0.11157683283090591; not saving weights
epoch 12



top10 acc train: 0.05427071452140808
top10 acc val: 0.05968647822737694
best score remains 0.11157683283090591; not saving weights
epoch 13



top10 acc train: 0.05370485037565231
top10 acc val: 0.062327101826667786
best score remains 0.11157683283090591; not saving weights
epoch 14



top10 acc train: 0.057309623807668686
top10 acc val: 0.05905775725841522
best score remains 0.11157683283090591; not saving weights
epoch 15



top10 acc train: 0.05511951446533203
top10 acc val: 0.06249476224184036
best score remains 0.11157683283090591; not saving weights
epoch 16



top10 acc train: 0.056125495582818985
top10 acc val: 0.04941738769412041
best score remains 0.11157683283090591; not saving weights
epoch 17



top10 acc train: 0.05342191457748413
top10 acc val: 0.05583032965660095
best score remains 0.11157683283090591; not saving weights
epoch 18



top10 acc train: 0.05215395614504814
top10 acc val: 0.05440523102879524
best score remains 0.11157683283090591; not saving weights
epoch 19



top10 acc train: 0.05662848800420761
top10 acc val: 0.05800989270210266
best score remains 0.11157683283090591; not saving weights
epoch 20



top10 acc train: 0.05843087658286095
top10 acc val: 0.059476904571056366
best score remains 0.11157683283090591; not saving weights
epoch 21



top10 acc train: 0.061930861324071884
top10 acc val: 0.06391985714435577
best score remains 0.11157683283090591; not saving weights
epoch 22



top10 acc train: 0.06179463118314743
top10 acc val: 0.062033697962760925
best score remains 0.11157683283090591; not saving weights
epoch 23



top10 acc train: 0.06143834814429283
top10 acc val: 0.06132115051150322
best score remains 0.11157683283090591; not saving weights
epoch 24



top10 acc train: 0.06755807995796204
top10 acc val: 0.06350070983171463
best score remains 0.11157683283090591; not saving weights
epoch 25



top10 acc train: 0.06813442707061768
top10 acc val: 0.07154832780361176
best score remains 0.11157683283090591; not saving weights
epoch 26



top10 acc train: 0.07355206459760666
top10 acc val: 0.07381171733140945
best score remains 0.11157683283090591; not saving weights
epoch 27



top10 acc train: 0.07216883450746536
top10 acc val: 0.06542878597974777
best score remains 0.11157683283090591; not saving weights
epoch 28



top10 acc train: 0.06727514415979385
top10 acc val: 0.06987173855304718
best score remains 0.11157683283090591; not saving weights
epoch 29



top10 acc train: 0.06818681955337524
top10 acc val: 0.0697459951043129
best score remains 0.11157683283090591; not saving weights
epoch 30



top10 acc train: 0.07011495530605316
top10 acc val: 0.06588985025882721
best score remains 0.11157683283090591; not saving weights
epoch 31



top10 acc train: 0.06822873651981354
top10 acc val: 0.06664431095123291
best score remains 0.11157683283090591; not saving weights
epoch 32



top10 acc train: 0.07151913642883301
top10 acc val: 0.07318300008773804
best score remains 0.11157683283090591; not saving weights
epoch 33



top10 acc train: 0.0749562531709671
top10 acc val: 0.0719255581498146
best score remains 0.11157683283090591; not saving weights
epoch 34



top10 acc train: 0.07396074384450912
top10 acc val: 0.0772487223148346
best score remains 0.11157683283090591; not saving weights
epoch 35



top10 acc train: 0.0772092342376709
top10 acc val: 0.07221896201372147
best score remains 0.11157683283090591; not saving weights
epoch 36



top10 acc train: 0.07821521908044815
top10 acc val: 0.06781792640686035
best score remains 0.11157683283090591; not saving weights
epoch 37



top10 acc train: 0.0783933624625206
top10 acc val: 0.07477575540542603
best score remains 0.11157683283090591; not saving weights
epoch 38



top10 acc train: 0.08410441130399704
top10 acc val: 0.07506915926933289
best score remains 0.11157683283090591; not saving weights
epoch 39



top10 acc train: 0.08499512821435928
top10 acc val: 0.07515298575162888
best score remains 0.11157683283090591; not saving weights
epoch 40



top10 acc train: 0.09231994301080704
top10 acc val: 0.07875765115022659
best score remains 0.11157683283090591; not saving weights
epoch 41



top10 acc train: 0.0963229238986969
top10 acc val: 0.07553022354841232
best score remains 0.11157683283090591; not saving weights
epoch 42



top10 acc train: 0.0962810069322586
top10 acc val: 0.082404226064682
best score remains 0.11157683283090591; not saving weights
epoch 43



top10 acc train: 0.10202349722385406
top10 acc val: 0.08755972981452942
best score remains 0.11157683283090591; not saving weights
epoch 44



top10 acc train: 0.1086043044924736
top10 acc val: 0.09200268238782883
best score remains 0.11157683283090591; not saving weights
epoch 45



top10 acc train: 0.11622253060340881
top10 acc val: 0.09204459935426712
best score remains 0.11157683283090591; not saving weights
epoch 46



top10 acc train: 0.1181611493229866
top10 acc val: 0.09099672734737396
best score remains 0.11157683283090591; not saving weights
epoch 47



top10 acc train: 0.12015215307474136
top10 acc val: 0.08667951822280884
best score remains 0.11157683283090591; not saving weights
epoch 48



top10 acc train: 0.1270054131746292
top10 acc val: 0.09263139963150024
best score remains 0.11157683283090591; not saving weights
epoch 49



top10 acc train: 0.13270598649978638
top10 acc val: 0.09380501508712769
best score remains 0.11157683283090591; not saving weights
epoch 50



top10 acc train: 0.1342778354883194
top10 acc val: 0.09196076542139053
best score remains 0.11157683283090591; not saving weights
epoch 51



top10 acc train: 0.13759967684745789
top10 acc val: 0.08663760870695114
best score remains 0.11157683283090591; not saving weights
epoch 52



top10 acc train: 0.14054428040981293
top10 acc val: 0.09334395080804825
best score remains 0.11157683283090591; not saving weights
epoch 53



top10 acc train: 0.14950381219387054
top10 acc val: 0.09661329537630081
best score remains 0.11157683283090591; not saving weights
epoch 54



top10 acc train: 0.15517295897006989
top10 acc val: 0.09875094145536423
best score remains 0.11157683283090591; not saving weights
epoch 55



top10 acc train: 0.1623196303844452
top10 acc val: 0.10139156877994537
best score remains 0.11157683283090591; not saving weights
epoch 56



top10 acc train: 0.1694243848323822
top10 acc val: 0.10809791088104248
best score remains 0.11157683283090591; not saving weights
epoch 57



top10 acc train: 0.17757704854011536
top10 acc val: 0.11790594458580017
new best score: 0.11790594458580017; saving weights @ models/last_run_weights.h5py
epoch 58



top10 acc train: 0.18686144053936005
top10 acc val: 0.11421745270490646
best score remains 0.11790594458580017; not saving weights
epoch 59



top10 acc train: 0.18670424818992615
top10 acc val: 0.11819934844970703
new best score: 0.11819934844970703; saving weights @ models/last_run_weights.h5py
epoch 60



top10 acc train: 0.19571618735790253
top10 acc val: 0.12234889715909958
new best score: 0.12234889715909958; saving weights @ models/last_run_weights.h5py
epoch 61



top10 acc train: 0.2061113566160202
top10 acc val: 0.13219884037971497
new best score: 0.13219884037971497; saving weights @ models/last_run_weights.h5py
epoch 62



top10 acc train: 0.21668465435504913
top10 acc val: 0.13588733971118927
new best score: 0.13588733971118927; saving weights @ models/last_run_weights.h5py
epoch 63



top10 acc train: 0.22565467655658722
top10 acc val: 0.13618072867393494
new best score: 0.13618072867393494; saving weights @ models/last_run_weights.h5py
epoch 64



top10 acc train: 0.2284211367368698
top10 acc val: 0.1393662542104721
new best score: 0.1393662542104721; saving weights @ models/last_run_weights.h5py
epoch 65



top10 acc train: 0.24044053256511688
top10 acc val: 0.1485036462545395
new best score: 0.1485036462545395; saving weights @ models/last_run_weights.h5py
epoch 66



top10 acc train: 0.24913810193538666
top10 acc val: 0.1520663946866989
new best score: 0.1520663946866989; saving weights @ models/last_run_weights.h5py
epoch 67



top10 acc train: 0.25679823756217957
top10 acc val: 0.15629976987838745
new best score: 0.15629976987838745; saving weights @ models/last_run_weights.h5py
epoch 68



top10 acc train: 0.2612413465976715
top10 acc val: 0.15491658449172974
best score remains 0.15629976987838745; not saving weights
epoch 69



top10 acc train: 0.27118590474128723
top10 acc val: 0.16376058757305145
new best score: 0.16376058757305145; saving weights @ models/last_run_weights.h5py
epoch 70



top10 acc train: 0.2768760025501251
top10 acc val: 0.1701735258102417
new best score: 0.1701735258102417; saving weights @ models/last_run_weights.h5py
epoch 71



top10 acc train: 0.28388646245002747
top10 acc val: 0.16661077737808228
best score remains 0.1701735258102417; not saving weights
epoch 72



top10 acc train: 0.2880675792694092
top10 acc val: 0.17344287037849426
new best score: 0.17344287037849426; saving weights @ models/last_run_weights.h5py
epoch 73



top10 acc train: 0.2975301146507263
top10 acc val: 0.1806941032409668
new best score: 0.1806941032409668; saving weights @ models/last_run_weights.h5py
epoch 74



top10 acc train: 0.3040899634361267
top10 acc val: 0.18195155262947083
new best score: 0.18195155262947083; saving weights @ models/last_run_weights.h5py
epoch 75



top10 acc train: 0.3020360767841339
top10 acc val: 0.17813731729984283
best score remains 0.18195155262947083; not saving weights
epoch 76



top10 acc train: 0.310492604970932
top10 acc val: 0.18756811320781708
new best score: 0.18756811320781708; saving weights @ models/last_run_weights.h5py
epoch 77



top10 acc train: 0.31991323828697205
top10 acc val: 0.19138234853744507
new best score: 0.19138234853744507; saving weights @ models/last_run_weights.h5py
epoch 78



top10 acc train: 0.32523655891418457
top10 acc val: 0.19444212317466736
new best score: 0.19444212317466736; saving weights @ models/last_run_weights.h5py
epoch 79



top10 acc train: 0.32927098870277405
top10 acc val: 0.19838209450244904
new best score: 0.19838209450244904; saving weights @ models/last_run_weights.h5py
epoch 80



top10 acc train: 0.33902692794799805
top10 acc val: 0.19926230609416962
new best score: 0.19926230609416962; saving weights @ models/last_run_weights.h5py
epoch 81



top10 acc train: 0.34463319182395935
top10 acc val: 0.20747756958007812
new best score: 0.20747756958007812; saving weights @ models/last_run_weights.h5py
epoch 82



top10 acc train: 0.35328882932662964
top10 acc val: 0.2099086195230484
new best score: 0.2099086195230484; saving weights @ models/last_run_weights.h5py
epoch 83



top10 acc train: 0.3537708520889282
top10 acc val: 0.20487886667251587
best score remains 0.2099086195230484; not saving weights
epoch 84



top10 acc train: 0.35734421014785767
top10 acc val: 0.20932182669639587
best score remains 0.2099086195230484; not saving weights
epoch 85



top10 acc train: 0.3610118627548218
top10 acc val: 0.2128007411956787
new best score: 0.2128007411956787; saving weights @ models/last_run_weights.h5py
epoch 86



top10 acc train: 0.36651331186294556
top10 acc val: 0.22206388413906097
new best score: 0.22206388413906097; saving weights @ models/last_run_weights.h5py
epoch 87



top10 acc train: 0.37120792269706726
top10 acc val: 0.22286026179790497
new best score: 0.22286026179790497; saving weights @ models/last_run_weights.h5py
epoch 88



top10 acc train: 0.3778725564479828
top10 acc val: 0.22252494096755981
best score remains 0.22286026179790497; not saving weights
epoch 89



top10 acc train: 0.3810372054576874
top10 acc val: 0.22604577243328094
new best score: 0.22604577243328094; saving weights @ models/last_run_weights.h5py
epoch 90



top10 acc train: 0.38724076747894287
top10 acc val: 0.22918936610221863
new best score: 0.22918936610221863; saving weights @ models/last_run_weights.h5py
epoch 91



top10 acc train: 0.3936958312988281
top10 acc val: 0.23338083922863007
new best score: 0.23338083922863007; saving weights @ models/last_run_weights.h5py
epoch 92



top10 acc train: 0.3982017934322357
top10 acc val: 0.23329700529575348
best score remains 0.23338083922863007; not saving weights
epoch 93



top10 acc train: 0.4015341103076935
top10 acc val: 0.23857825994491577
new best score: 0.23857825994491577; saving weights @ models/last_run_weights.h5py
epoch 94



top10 acc train: 0.40730804204940796
top10 acc val: 0.23970994353294373
new best score: 0.23970994353294373; saving weights @ models/last_run_weights.h5py
epoch 95



top10 acc train: 0.4085969626903534
top10 acc val: 0.24566183984279633
new best score: 0.24566183984279633; saving weights @ models/last_run_weights.h5py
epoch 96



top10 acc train: 0.4129457473754883
top10 acc val: 0.2451169490814209
best score remains 0.24566183984279633; not saving weights
epoch 97



top10 acc train: 0.4149996340274811
top10 acc val: 0.24352417886257172
best score remains 0.24566183984279633; not saving weights
epoch 98



top10 acc train: 0.41718974709510803
top10 acc val: 0.2474641650915146
new best score: 0.2474641650915146; saving weights @ models/last_run_weights.h5py
epoch 99



top10 acc train: 0.41971516609191895
top10 acc val: 0.24490736424922943
best score remains 0.2474641650915146; not saving weights
epoch 100



top10 acc train: 0.42175859212875366
top10 acc val: 0.2510688304901123
new best score: 0.2510688304901123; saving weights @ models/last_run_weights.h5py
epoch 101



top10 acc train: 0.42618072032928467
top10 acc val: 0.25366753339767456
new best score: 0.25366753339767456; saving weights @ models/last_run_weights.h5py
epoch 102



top10 acc train: 0.429135799407959
top10 acc val: 0.25245201587677
best score remains 0.25366753339767456; not saving weights
epoch 103



top10 acc train: 0.43330642580986023
top10 acc val: 0.2557632625102997
new best score: 0.2557632625102997; saving weights @ models/last_run_weights.h5py
epoch 104



top10 acc train: 0.4330025315284729
top10 acc val: 0.25521838665008545
best score remains 0.2557632625102997; not saving weights
epoch 105



top10 acc train: 0.43839922547340393
top10 acc val: 0.2586134672164917
new best score: 0.2586134672164917; saving weights @ models/last_run_weights.h5py
epoch 106



top10 acc train: 0.44242316484451294
top10 acc val: 0.26435577869415283
new best score: 0.26435577869415283; saving weights @ models/last_run_weights.h5py
epoch 107



top10 acc train: 0.4460698664188385
top10 acc val: 0.2595355808734894
best score remains 0.26435577869415283; not saving weights
epoch 108



top10 acc train: 0.44873151183128357
top10 acc val: 0.26511022448539734
new best score: 0.26511022448539734; saving weights @ models/last_run_weights.h5py
epoch 109



top10 acc train: 0.4524306058883667
top10 acc val: 0.26716405153274536
new best score: 0.26716405153274536; saving weights @ models/last_run_weights.h5py
epoch 110



top10 acc train: 0.45572102069854736
top10 acc val: 0.26879873871803284
new best score: 0.26879873871803284; saving weights @ models/last_run_weights.h5py
epoch 111



top10 acc train: 0.4614006280899048
top10 acc val: 0.27240338921546936
new best score: 0.27240338921546936; saving weights @ models/last_run_weights.h5py
epoch 112



top10 acc train: 0.46098145842552185
top10 acc val: 0.27563080191612244
new best score: 0.27563080191612244; saving weights @ models/last_run_weights.h5py
epoch 113



top10 acc train: 0.464229941368103
top10 acc val: 0.27693018317222595
new best score: 0.27693018317222595; saving weights @ models/last_run_weights.h5py
epoch 114



top10 acc train: 0.4669335186481476
top10 acc val: 0.2749601900577545
best score remains 0.27693018317222595; not saving weights
epoch 115



top10 acc train: 0.4686206579208374
top10 acc val: 0.27542123198509216
best score remains 0.27693018317222595; not saving weights
epoch 116



top10 acc train: 0.4700353145599365
top10 acc val: 0.28137311339378357
new best score: 0.28137311339378357; saving weights @ models/last_run_weights.h5py
epoch 117



top10 acc train: 0.47413259744644165
top10 acc val: 0.2801995277404785
best score remains 0.28137311339378357; not saving weights
epoch 118



top10 acc train: 0.4755263030529022
top10 acc val: 0.27919355034828186
best score remains 0.28137311339378357; not saving weights
epoch 119



top10 acc train: 0.4760397672653198
top10 acc val: 0.2796127200126648
best score remains 0.28137311339378357; not saving weights
epoch 120



top10 acc train: 0.4807972311973572
top10 acc val: 0.2862352132797241
new best score: 0.2862352132797241; saving weights @ models/last_run_weights.h5py
epoch 121



top10 acc train: 0.48503077030181885
top10 acc val: 0.28439098596572876
best score remains 0.2862352132797241; not saving weights
epoch 122



top10 acc train: 0.4875352382659912
top10 acc val: 0.2877441644668579
new best score: 0.2877441644668579; saving weights @ models/last_run_weights.h5py
epoch 123



top10 acc train: 0.49029120802879333
top10 acc val: 0.2893369197845459
new best score: 0.2893369197845459; saving weights @ models/last_run_weights.h5py
epoch 124



top10 acc train: 0.49321484565734863
top10 acc val: 0.2900913655757904
new best score: 0.2900913655757904; saving weights @ models/last_run_weights.h5py
epoch 125



top10 acc train: 0.4945980906486511
top10 acc val: 0.29130691289901733
new best score: 0.29130691289901733; saving weights @ models/last_run_weights.h5py
epoch 126



top10 acc train: 0.49707111716270447
top10 acc val: 0.29357028007507324
new best score: 0.29357028007507324; saving weights @ models/last_run_weights.h5py
epoch 127



top10 acc train: 0.49743789434432983
top10 acc val: 0.29516303539276123
new best score: 0.29516303539276123; saving weights @ models/last_run_weights.h5py
epoch 128



top10 acc train: 0.5013465285301208
top10 acc val: 0.2930673062801361
best score remains 0.29516303539276123; not saving weights
epoch 129



top10 acc train: 0.5017028450965881
top10 acc val: 0.29730069637298584
new best score: 0.29730069637298584; saving weights @ models/last_run_weights.h5py
epoch 130



top10 acc train: 0.5067851543426514
top10 acc val: 0.29730069637298584
best score remains 0.29730069637298584; not saving weights
epoch 131



top10 acc train: 0.5087133049964905
top10 acc val: 0.3012825846672058
new best score: 0.3012825846672058; saving weights @ models/last_run_weights.h5py
epoch 132



top10 acc train: 0.5110501050949097
top10 acc val: 0.2996479272842407
best score remains 0.3012825846672058; not saving weights
epoch 133



top10 acc train: 0.5121713280677795
top10 acc val: 0.2975102663040161
best score remains 0.3012825846672058; not saving weights
epoch 134



top10 acc train: 0.5098659992218018
top10 acc val: 0.2998155653476715
best score remains 0.3012825846672058; not saving weights
epoch 135



top10 acc train: 0.5129362940788269
top10 acc val: 0.3013245165348053
new best score: 0.3013245165348053; saving weights @ models/last_run_weights.h5py
epoch 136



top10 acc train: 0.5170650482177734
top10 acc val: 0.3043423593044281
new best score: 0.3043423593044281; saving weights @ models/last_run_weights.h5py
epoch 137



top10 acc train: 0.5231114029884338
top10 acc val: 0.3049710690975189
new best score: 0.3049710690975189; saving weights @ models/last_run_weights.h5py
epoch 138



top10 acc train: 0.5227446556091309
top10 acc val: 0.30857574939727783
new best score: 0.30857574939727783; saving weights @ models/last_run_weights.h5py
epoch 139



top10 acc train: 0.5230485200881958
top10 acc val: 0.3059351146221161
best score remains 0.30857574939727783; not saving weights
epoch 140



top10 acc train: 0.5278793573379517
top10 acc val: 0.30861765146255493
new best score: 0.30861765146255493; saving weights @ models/last_run_weights.h5py
epoch 141



top10 acc train: 0.5312745571136475
top10 acc val: 0.31000083684921265
new best score: 0.31000083684921265; saving weights @ models/last_run_weights.h5py
epoch 142



top10 acc train: 0.5323224663734436
top10 acc val: 0.31213849782943726
new best score: 0.31213849782943726; saving weights @ models/last_run_weights.h5py
epoch 143



top10 acc train: 0.5354661345481873
top10 acc val: 0.3119708299636841
best score remains 0.31213849782943726; not saving weights
epoch 144



top10 acc train: 0.5382221341133118
top10 acc val: 0.31536591053009033
new best score: 0.31536591053009033; saving weights @ models/last_run_weights.h5py
epoch 145



top10 acc train: 0.5408104658126831
top10 acc val: 0.3172101676464081
new best score: 0.3172101676464081; saving weights @ models/last_run_weights.h5py
epoch 146



top10 acc train: 0.543304443359375
top10 acc val: 0.31813228130340576
new best score: 0.31813228130340576; saving weights @ models/last_run_weights.h5py
epoch 147



top10 acc train: 0.5454211831092834
top10 acc val: 0.3154497444629669
best score remains 0.31813228130340576; not saving weights
epoch 148



top10 acc train: 0.5469406843185425
top10 acc val: 0.31603655219078064
best score remains 0.31813228130340576; not saving weights
epoch 149



top10 acc train: 0.5466891527175903
top10 acc val: 0.3180484473705292
best score remains 0.31813228130340576; not saving weights
epoch 150



top10 acc train: 0.5440589189529419
top10 acc val: 0.31368932127952576
best score remains 0.31813228130340576; not saving weights
epoch 151



top10 acc train: 0.5429691076278687
top10 acc val: 0.31440186500549316
best score remains 0.31813228130340576; not saving weights
epoch 152



top10 acc train: 0.5445829033851624
top10 acc val: 0.32035374641418457
new best score: 0.32035374641418457; saving weights @ models/last_run_weights.h5py
epoch 153



top10 acc train: 0.548606812953949
top10 acc val: 0.32052141427993774
new best score: 0.32052141427993774; saving weights @ models/last_run_weights.h5py
epoch 154



top10 acc train: 0.5466053485870361
top10 acc val: 0.32115012407302856
new best score: 0.32115012407302856; saving weights @ models/last_run_weights.h5py
epoch 155



top10 acc train: 0.5460184812545776
top10 acc val: 0.3194316327571869
best score remains 0.32115012407302856; not saving weights
epoch 156



top10 acc train: 0.5437759757041931
top10 acc val: 0.3178388774394989
best score remains 0.32115012407302856; not saving weights
epoch 157



top10 acc train: 0.5480409264564514
top10 acc val: 0.3193897306919098
best score remains 0.32115012407302856; not saving weights
epoch 158



top10 acc train: 0.5491517186164856
top10 acc val: 0.3224495053291321
new best score: 0.3224495053291321; saving weights @ models/last_run_weights.h5py
epoch 159



top10 acc train: 0.5538986921310425
top10 acc val: 0.3266409635543823
new best score: 0.3266409635543823; saving weights @ models/last_run_weights.h5py
epoch 160



top10 acc train: 0.5581846237182617
top10 acc val: 0.3259284198284149
best score remains 0.3266409635543823; not saving weights
epoch 161



top10 acc train: 0.5612863898277283
top10 acc val: 0.32802414894104004
new best score: 0.32802414894104004; saving weights @ models/last_run_weights.h5py
epoch 162



top10 acc train: 0.5659705400466919
top10 acc val: 0.3321317732334137
new best score: 0.3321317732334137; saving weights @ models/last_run_weights.h5py
epoch 163



top10 acc train: 0.5679405927658081
top10 acc val: 0.3333892226219177
new best score: 0.3333892226219177; saving weights @ models/last_run_weights.h5py
epoch 164



top10 acc train: 0.5715977549552917
top10 acc val: 0.3330119848251343
best score remains 0.3333892226219177; not saving weights
epoch 165



top10 acc train: 0.5737144947052002
top10 acc val: 0.33410176634788513
new best score: 0.33410176634788513; saving weights @ models/last_run_weights.h5py
epoch 166



top10 acc train: 0.5758941173553467
top10 acc val: 0.33632323145866394
new best score: 0.33632323145866394; saving weights @ models/last_run_weights.h5py
epoch 167



top10 acc train: 0.577046811580658
top10 acc val: 0.3379998207092285
new best score: 0.3379998207092285; saving weights @ models/last_run_weights.h5py
epoch 168



top10 acc train: 0.577560305595398
top10 acc val: 0.3396764099597931
new best score: 0.3396764099597931; saving weights @ models/last_run_weights.h5py
epoch 169



top10 acc train: 0.5780842304229736
top10 acc val: 0.33774834871292114
best score remains 0.3396764099597931; not saving weights
epoch 170



top10 acc train: 0.5797713398933411
top10 acc val: 0.33770641684532166
best score remains 0.3396764099597931; not saving weights
epoch 171



top10 acc train: 0.5831351280212402
top10 acc val: 0.3401374816894531
new best score: 0.3401374816894531; saving weights @ models/last_run_weights.h5py
epoch 172



top10 acc train: 0.585503339767456
top10 acc val: 0.3401793837547302
new best score: 0.3401793837547302; saving weights @ models/last_run_weights.h5py
epoch 173



top10 acc train: 0.5860692262649536
top10 acc val: 0.3439517021179199
new best score: 0.3439517021179199; saving weights @ models/last_run_weights.h5py
epoch 174



top10 acc train: 0.5869075655937195
top10 acc val: 0.3426104485988617
best score remains 0.3439517021179199; not saving weights
epoch 175



top10 acc train: 0.5833446979522705
top10 acc val: 0.33854472637176514
best score remains 0.3439517021179199; not saving weights
epoch 176



top10 acc train: 0.5808821320533752
top10 acc val: 0.3411853611469269
best score remains 0.3439517021179199; not saving weights
epoch 177



top10 acc train: 0.5763552188873291
top10 acc val: 0.3389638662338257
best score remains 0.3439517021179199; not saving weights
epoch 178



top10 acc train: 0.5754958987236023
top10 acc val: 0.3395506739616394
best score remains 0.3439517021179199; not saving weights
epoch 179



top10 acc train: 0.5715243816375732
top10 acc val: 0.3344790041446686
best score remains 0.3439517021179199; not saving weights
epoch 180



top10 acc train: 0.5694495439529419
top10 acc val: 0.335191547870636
best score remains 0.3439517021179199; not saving weights
epoch 181



top10 acc train: 0.5741651058197021
top10 acc val: 0.34001174569129944
best score remains 0.3439517021179199; not saving weights
epoch 182



top10 acc train: 0.5781785249710083
top10 acc val: 0.33996981382369995
best score remains 0.3439517021179199; not saving weights
epoch 183



top10 acc train: 0.5813327431678772
top10 acc val: 0.34382596611976624
best score remains 0.3439517021179199; not saving weights
epoch 184



top10 acc train: 0.5846335887908936
top10 acc val: 0.3431553244590759
best score remains 0.3439517021179199; not saving weights
epoch 185



top10 acc train: 0.5884689092636108
top10 acc val: 0.34583786129951477
new best score: 0.34583786129951477; saving weights @ models/last_run_weights.h5py
epoch 186



top10 acc train: 0.5911305546760559
top10 acc val: 0.3462989330291748
new best score: 0.3462989330291748; saving weights @ models/last_run_weights.h5py
epoch 187



top10 acc train: 0.5934674143791199
top10 acc val: 0.34810125827789307
new best score: 0.34810125827789307; saving weights @ models/last_run_weights.h5py
epoch 188



top10 acc train: 0.5951230525970459
top10 acc val: 0.3478916883468628
best score remains 0.34810125827789307; not saving weights
epoch 189



top10 acc train: 0.5970093011856079
top10 acc val: 0.3488138020038605
new best score: 0.3488138020038605; saving weights @ models/last_run_weights.h5py
epoch 190



top10 acc train: 0.5995661616325378
top10 acc val: 0.3492748737335205
new best score: 0.3492748737335205; saving weights @ models/last_run_weights.h5py
epoch 191



top10 acc train: 0.6010960936546326
top10 acc val: 0.34818509221076965
best score remains 0.3492748737335205; not saving weights
epoch 192



top10 acc train: 0.6025002598762512
top10 acc val: 0.35128676891326904
new best score: 0.35128676891326904; saving weights @ models/last_run_weights.h5py
epoch 193



top10 acc train: 0.6031290292739868
top10 acc val: 0.35053232312202454
best score remains 0.35128676891326904; not saving weights
epoch 194



top10 acc train: 0.605465829372406
top10 acc val: 0.3530052900314331
new best score: 0.3530052900314331; saving weights @ models/last_run_weights.h5py
epoch 195



top10 acc train: 0.607205331325531
top10 acc val: 0.35137060284614563
best score remains 0.3530052900314331; not saving weights
epoch 196



top10 acc train: 0.60677570104599
top10 acc val: 0.3514963388442993
best score remains 0.3530052900314331; not saving weights
epoch 197



top10 acc train: 0.6080960631370544
top10 acc val: 0.3530471920967102
new best score: 0.3530471920967102; saving weights @ models/last_run_weights.h5py
epoch 198



top10 acc train: 0.609908938407898
top10 acc val: 0.3540531396865845
new best score: 0.3540531396865845; saving weights @ models/last_run_weights.h5py
epoch 199



top10 acc train: 0.61076819896698
top10 acc val: 0.3562327027320862
new best score: 0.3562327027320862; saving weights @ models/last_run_weights.h5py
epoch 200



top10 acc train: 0.6119104027748108
top10 acc val: 0.3516640067100525
best score remains 0.3562327027320862; not saving weights
epoch 201



top10 acc train: 0.6119837760925293
top10 acc val: 0.3531310260295868
best score remains 0.3562327027320862; not saving weights
epoch 202



top10 acc train: 0.6108729839324951
top10 acc val: 0.34676000475883484
best score remains 0.3562327027320862; not saving weights
epoch 203



top10 acc train: 0.5938655734062195
top10 acc val: 0.3470953106880188
best score remains 0.3562327027320862; not saving weights
epoch 204



top10 acc train: 0.588144063949585
top10 acc val: 0.3506161570549011
best score remains 0.3562327027320862; not saving weights
epoch 205



top10 acc train: 0.5898416638374329
top10 acc val: 0.3471372425556183
best score remains 0.3562327027320862; not saving weights
epoch 206



top10 acc train: 0.5957728028297424
top10 acc val: 0.34893956780433655
best score remains 0.3562327027320862; not saving weights
epoch 207



top10 acc train: 0.5996814370155334
top10 acc val: 0.3543884754180908
best score remains 0.3562327027320862; not saving weights
epoch 208



top10 acc train: 0.6046379804611206
top10 acc val: 0.3575739860534668
new best score: 0.3575739860534668; saving weights @ models/last_run_weights.h5py
epoch 209



top10 acc train: 0.6096783876419067
top10 acc val: 0.3569871783256531
best score remains 0.3575739860534668; not saving weights
epoch 210



top10 acc train: 0.6123924851417542
top10 acc val: 0.35719674825668335
best score remains 0.3575739860534668; not saving weights
epoch 211



top10 acc train: 0.6151798963546753
top10 acc val: 0.35652610659599304
best score remains 0.3575739860534668; not saving weights
epoch 212



top10 acc train: 0.6146768927574158
top10 acc val: 0.35656803846359253
best score remains 0.3575739860534668; not saving weights
epoch 213



top10 acc train: 0.6173490285873413
top10 acc val: 0.3581607937812805
new best score: 0.3581607937812805; saving weights @ models/last_run_weights.h5py
epoch 214



top10 acc train: 0.6183130741119385
top10 acc val: 0.3561069667339325
best score remains 0.3581607937812805; not saving weights
epoch 215



top10 acc train: 0.6202831268310547
top10 acc val: 0.35807695984840393
best score remains 0.3581607937812805; not saving weights
epoch 216



top10 acc train: 0.6206289529800415
top10 acc val: 0.3584541976451874
new best score: 0.3584541976451874; saving weights @ models/last_run_weights.h5py
epoch 217



top10 acc train: 0.6219807267189026
top10 acc val: 0.35954397916793823
new best score: 0.35954397916793823; saving weights @ models/last_run_weights.h5py
epoch 218



top10 acc train: 0.6241079568862915
top10 acc val: 0.36025652289390564
new best score: 0.36025652289390564; saving weights @ models/last_run_weights.h5py
epoch 219



top10 acc train: 0.6248729228973389
top10 acc val: 0.36013078689575195
best score remains 0.36025652289390564; not saving weights
epoch 220



top10 acc train: 0.6262142658233643
top10 acc val: 0.36151397228240967
new best score: 0.36151397228240967; saving weights @ models/last_run_weights.h5py
epoch 221



top10 acc train: 0.627377450466156
top10 acc val: 0.36251991987228394
new best score: 0.36251991987228394; saving weights @ models/last_run_weights.h5py
epoch 222



top10 acc train: 0.6288444995880127
top10 acc val: 0.3620169460773468
best score remains 0.36251991987228394; not saving weights
epoch 223



top10 acc train: 0.6302696466445923
top10 acc val: 0.3628552258014679
new best score: 0.3628552258014679; saving weights @ models/last_run_weights.h5py
epoch 224



top10 acc train: 0.6316109299659729
top10 acc val: 0.3611367344856262
best score remains 0.3628552258014679; not saving weights
epoch 225



top10 acc train: 0.6314432621002197
top10 acc val: 0.36327436566352844
new best score: 0.36327436566352844; saving weights @ models/last_run_weights.h5py
epoch 226



top10 acc train: 0.6328160166740417
top10 acc val: 0.36239415407180786
best score remains 0.36327436566352844; not saving weights
epoch 227



top10 acc train: 0.6348908543586731
top10 acc val: 0.3635258674621582
new best score: 0.3635258674621582; saving weights @ models/last_run_weights.h5py
epoch 228



top10 acc train: 0.6351004242897034
top10 acc val: 0.36105290055274963
best score remains 0.3635258674621582; not saving weights
epoch 229



top10 acc train: 0.6364522576332092
top10 acc val: 0.3629809617996216
best score remains 0.3635258674621582; not saving weights
epoch 230



top10 acc train: 0.6381602883338928
top10 acc val: 0.36390310525894165
new best score: 0.36390310525894165; saving weights @ models/last_run_weights.h5py
epoch 231



top10 acc train: 0.6382965445518494
top10 acc val: 0.36474138498306274
new best score: 0.36474138498306274; saving weights @ models/last_run_weights.h5py
epoch 232



top10 acc train: 0.6352576017379761
top10 acc val: 0.36231034994125366
best score remains 0.36474138498306274; not saving weights
epoch 233



top10 acc train: 0.6186589002609253
top10 acc val: 0.3540112376213074
best score remains 0.36474138498306274; not saving weights
epoch 234



top10 acc train: 0.6070586442947388
top10 acc val: 0.35329869389533997
best score remains 0.36474138498306274; not saving weights
epoch 235



top10 acc train: 0.6024688482284546
top10 acc val: 0.35417890548706055
best score remains 0.36474138498306274; not saving weights
epoch 236



top10 acc train: 0.6054449081420898
top10 acc val: 0.35355016589164734
best score remains 0.36474138498306274; not saving weights
epoch 237



top10 acc train: 0.6109673380851746
top10 acc val: 0.3568195104598999
best score remains 0.36474138498306274; not saving weights
epoch 238



top10 acc train: 0.6156724095344543
top10 acc val: 0.3561908006668091
best score remains 0.36474138498306274; not saving weights
epoch 239



top10 acc train: 0.6212367415428162
top10 acc val: 0.36013078689575195
best score remains 0.36474138498306274; not saving weights
epoch 240



top10 acc train: 0.6244328022003174
top10 acc val: 0.3606756627559662
best score remains 0.36474138498306274; not saving weights
epoch 241



top10 acc train: 0.62766033411026
top10 acc val: 0.36105290055274963
best score remains 0.36474138498306274; not saving weights
epoch 242



top10 acc train: 0.6309926509857178
top10 acc val: 0.35929247736930847
best score remains 0.36474138498306274; not saving weights
epoch 243



top10 acc train: 0.6328684091567993
top10 acc val: 0.36231034994125366
best score remains 0.36474138498306274; not saving weights
epoch 244



top10 acc train: 0.6347022652626038
top10 acc val: 0.36327436566352844
best score remains 0.36474138498306274; not saving weights
epoch 245



top10 acc train: 0.6370914578437805
top10 acc val: 0.36478328704833984
new best score: 0.36478328704833984; saving weights @ models/last_run_weights.h5py
epoch 246



top10 acc train: 0.6374372839927673
top10 acc val: 0.3665018081665039
new best score: 0.3665018081665039; saving weights @ models/last_run_weights.h5py
epoch 247



top10 acc train: 0.639784574508667
top10 acc val: 0.36532819271087646
best score remains 0.3665018081665039; not saving weights
epoch 248



top10 acc train: 0.6403399109840393
top10 acc val: 0.36692094802856445
new best score: 0.36692094802856445; saving weights @ models/last_run_weights.h5py
epoch 249



top10 acc train: 0.6417441368103027
top10 acc val: 0.36532819271087646
best score remains 0.36692094802856445; not saving weights
epoch 250



top10 acc train: 0.642896831035614
top10 acc val: 0.36771732568740845
new best score: 0.36771732568740845; saving weights @ models/last_run_weights.h5py
epoch 251



top10 acc train: 0.6448354125022888
top10 acc val: 0.36692094802856445
best score remains 0.36771732568740845; not saving weights
epoch 252



top10 acc train: 0.6454851031303406
top10 acc val: 0.3665856420993805
best score remains 0.36771732568740845; not saving weights
epoch 253



top10 acc train: 0.6463024616241455
top10 acc val: 0.3667113780975342
best score remains 0.36771732568740845; not saving weights
epoch 254



top10 acc train: 0.6462920308113098
top10 acc val: 0.3675496578216553
best score remains 0.36771732568740845; not saving weights
epoch 255



top10 acc train: 0.6480105519294739
top10 acc val: 0.3717411458492279
new best score: 0.3717411458492279; saving weights @ models/last_run_weights.h5py
epoch 256



top10 acc train: 0.6497396230697632
top10 acc val: 0.36700478196144104
best score remains 0.3717411458492279; not saving weights
epoch 257



top10 acc train: 0.6495195627212524
top10 acc val: 0.3703160285949707
best score remains 0.3717411458492279; not saving weights
epoch 258



top10 acc train: 0.6514581441879272
top10 acc val: 0.37207645177841187
new best score: 0.37207645177841187; saving weights @ models/last_run_weights.h5py
epoch 259



top10 acc train: 0.6530404686927795
top10 acc val: 0.3710285723209381
best score remains 0.37207645177841187; not saving weights
epoch 260



top10 acc train: 0.6525479555130005
top10 acc val: 0.36989688873291016
best score remains 0.37207645177841187; not saving weights
epoch 261



top10 acc train: 0.6516048312187195
top10 acc val: 0.371783047914505
best score remains 0.37207645177841187; not saving weights
epoch 262



top10 acc train: 0.6409686803817749
top10 acc val: 0.3657054305076599
best score remains 0.37207645177841187; not saving weights
epoch 263



top10 acc train: 0.6355720162391663
top10 acc val: 0.3667113780975342
best score remains 0.37207645177841187; not saving weights
epoch 264



top10 acc train: 0.6327741146087646
top10 acc val: 0.3675496578216553
best score remains 0.37207645177841187; not saving weights
epoch 265



top10 acc train: 0.628603458404541
top10 acc val: 0.3664598762989044
best score remains 0.37207645177841187; not saving weights
epoch 266



top10 acc train: 0.633989691734314
top10 acc val: 0.37069326639175415
best score remains 0.37207645177841187; not saving weights
epoch 267



top10 acc train: 0.6430854201316833
top10 acc val: 0.3742141127586365
new best score: 0.3742141127586365; saving weights @ models/last_run_weights.h5py
epoch 268



top10 acc train: 0.6473503708839417
top10 acc val: 0.3749266564846039
new best score: 0.3749266564846039; saving weights @ models/last_run_weights.h5py
epoch 269



top10 acc train: 0.6496243476867676
top10 acc val: 0.3742141127586365
best score remains 0.3749266564846039; not saving weights
epoch 270



top10 acc train: 0.6514057517051697
top10 acc val: 0.3727470934391022
best score remains 0.3749266564846039; not saving weights
epoch 271



top10 acc train: 0.6518982648849487
top10 acc val: 0.37366920709609985
best score remains 0.3749266564846039; not saving weights
epoch 272



top10 acc train: 0.6541721820831299
top10 acc val: 0.37534579634666443
new best score: 0.37534579634666443; saving weights @ models/last_run_weights.h5py
epoch 273



top10 acc train: 0.6561213135719299
top10 acc val: 0.3762679100036621
new best score: 0.3762679100036621; saving weights @ models/last_run_weights.h5py
epoch 274



top10 acc train: 0.6575883626937866
top10 acc val: 0.3763517439365387
new best score: 0.3763517439365387; saving weights @ models/last_run_weights.h5py
epoch 275



top10 acc train: 0.6588039398193359
top10 acc val: 0.375764936208725
best score remains 0.3763517439365387; not saving weights
epoch 276



top10 acc train: 0.6586257815361023
top10 acc val: 0.37513622641563416
best score remains 0.3763517439365387; not saving weights
epoch 277



top10 acc train: 0.6601976156234741
top10 acc val: 0.37664514780044556
new best score: 0.37664514780044556; saving weights @ models/last_run_weights.h5py
epoch 278



top10 acc train: 0.6618742942810059
top10 acc val: 0.3777349293231964
new best score: 0.3777349293231964; saving weights @ models/last_run_weights.h5py
epoch 279



top10 acc train: 0.663267970085144
top10 acc val: 0.3784055709838867
new best score: 0.3784055709838867; saving weights @ models/last_run_weights.h5py
epoch 280



top10 acc train: 0.6646931171417236
top10 acc val: 0.3772738575935364
best score remains 0.3784055709838867; not saving weights
epoch 281



top10 acc train: 0.6652694940567017
top10 acc val: 0.37685471773147583
best score remains 0.3784055709838867; not saving weights
epoch 282



top10 acc train: 0.6657305359840393
top10 acc val: 0.37978875637054443
new best score: 0.37978875637054443; saving weights @ models/last_run_weights.h5py
epoch 283



top10 acc train: 0.6676377058029175
top10 acc val: 0.37882471084594727
best score remains 0.37978875637054443; not saving weights
epoch 284



top10 acc train: 0.6682140827178955
top10 acc val: 0.3784894049167633
best score remains 0.37978875637054443; not saving weights
epoch 285



top10 acc train: 0.668937087059021
top10 acc val: 0.3794953525066376
best score remains 0.37978875637054443; not saving weights
epoch 286



top10 acc train: 0.6701107621192932
top10 acc val: 0.3800821602344513
new best score: 0.3800821602344513; saving weights @ models/last_run_weights.h5py
epoch 287



top10 acc train: 0.6695553660392761
top10 acc val: 0.37886661291122437
best score remains 0.3800821602344513; not saving weights
epoch 288



top10 acc train: 0.6714625358581543
top10 acc val: 0.37983065843582153
best score remains 0.3800821602344513; not saving weights
epoch 289



top10 acc train: 0.6716406941413879
top10 acc val: 0.38054320216178894
new best score: 0.38054320216178894; saving weights @ models/last_run_weights.h5py
epoch 290



top10 acc train: 0.6701107621192932
top10 acc val: 0.37886661291122437
best score remains 0.38054320216178894; not saving weights
epoch 291



top10 acc train: 0.6713892221450806
top10 acc val: 0.38175874948501587
new best score: 0.38175874948501587; saving weights @ models/last_run_weights.h5py
epoch 292



top10 acc train: 0.6715044975280762
top10 acc val: 0.379411518573761
best score remains 0.38175874948501587; not saving weights
epoch 293



top10 acc train: 0.6702679395675659
top10 acc val: 0.3814234137535095
best score remains 0.38175874948501587; not saving weights
epoch 294



top10 acc train: 0.6639596223831177
top10 acc val: 0.37899237871170044
best score remains 0.38175874948501587; not saving weights
epoch 295



top10 acc train: 0.6482201218605042
top10 acc val: 0.36989688873291016
best score remains 0.38175874948501587; not saving weights
epoch 296



top10 acc train: 0.6407067179679871
top10 acc val: 0.36998072266578674
best score remains 0.38175874948501587; not saving weights
epoch 297



top10 acc train: 0.6456947326660156
top10 acc val: 0.37291473150253296
best score remains 0.38175874948501587; not saving weights
epoch 298



top10 acc train: 0.6537530422210693
top10 acc val: 0.3813815116882324
best score remains 0.38175874948501587; not saving weights
epoch 299



top10 acc train: 0.6553563475608826
top10 acc val: 0.37756726145744324
best score remains 0.38175874948501587; not saving weights
epoch 300



top10 acc train: 0.6591811776161194
top10 acc val: 0.37802833318710327
best score remains 0.38175874948501587; not saving weights
epoch 301



top10 acc train: 0.6595374345779419
top10 acc val: 0.37832173705101013
best score remains 0.38175874948501587; not saving weights
epoch 302



top10 acc train: 0.6628278493881226
top10 acc val: 0.3786570429801941
best score remains 0.38175874948501587; not saving weights
epoch 303



top10 acc train: 0.6657305359840393
top10 acc val: 0.3807108700275421
best score remains 0.38175874948501587; not saving weights
epoch 304



top10 acc train: 0.6667994260787964
top10 acc val: 0.38037556409835815
best score remains 0.38175874948501587; not saving weights
epoch 305



top10 acc train: 0.6686961054801941
top10 acc val: 0.3779025971889496
best score remains 0.38175874948501587; not saving weights
epoch 306



top10 acc train: 0.6697859168052673
top10 acc val: 0.38175874948501587
best score remains 0.38175874948501587; not saving weights
epoch 307



top10 acc train: 0.6709805130958557
top10 acc val: 0.3823455572128296
new best score: 0.3823455572128296; saving weights @ models/last_run_weights.h5py
epoch 308



top10 acc train: 0.6742185354232788
top10 acc val: 0.3815072476863861
best score remains 0.3823455572128296; not saving weights
epoch 309



top10 acc train: 0.674019455909729
top10 acc val: 0.38205215334892273
best score remains 0.3823455572128296; not saving weights
epoch 310



top10 acc train: 0.6750149130821228
top10 acc val: 0.38184258341789246
best score remains 0.3823455572128296; not saving weights
epoch 311



top10 acc train: 0.6766601204872131
top10 acc val: 0.38343533873558044
new best score: 0.38343533873558044; saving weights @ models/last_run_weights.h5py
epoch 312



top10 acc train: 0.6777814030647278
top10 acc val: 0.3830161690711975
best score remains 0.38343533873558044; not saving weights
epoch 313



top10 acc train: 0.6790807843208313
top10 acc val: 0.383854478597641
new best score: 0.383854478597641; saving weights @ models/last_run_weights.h5py
epoch 314



top10 acc train: 0.6801286935806274
top10 acc val: 0.38263896107673645
best score remains 0.383854478597641; not saving weights
epoch 315



top10 acc train: 0.6803172826766968
top10 acc val: 0.38423171639442444
new best score: 0.38423171639442444; saving weights @ models/last_run_weights.h5py
epoch 316



top10 acc train: 0.6813442707061768
top10 acc val: 0.38268086314201355
best score remains 0.38423171639442444; not saving weights
epoch 317



top10 acc train: 0.6817529201507568
top10 acc val: 0.38406404852867126
best score remains 0.38423171639442444; not saving weights
epoch 318



top10 acc train: 0.6829370260238647
top10 acc val: 0.3854053020477295
new best score: 0.3854053020477295; saving weights @ models/last_run_weights.h5py
epoch 319



top10 acc train: 0.6842573881149292
top10 acc val: 0.3854891359806061
new best score: 0.3854891359806061; saving weights @ models/last_run_weights.h5py
epoch 320



top10 acc train: 0.6851271390914917
top10 acc val: 0.38506999611854553
best score remains 0.3854891359806061; not saving weights
epoch 321



top10 acc train: 0.6856406331062317
top10 acc val: 0.38632744550704956
new best score: 0.38632744550704956; saving weights @ models/last_run_weights.h5py
epoch 322



top10 acc train: 0.6863951086997986
top10 acc val: 0.3866208493709564
new best score: 0.3866208493709564; saving weights @ models/last_run_weights.h5py
epoch 323



top10 acc train: 0.6864579916000366
top10 acc val: 0.38574063777923584
best score remains 0.3866208493709564; not saving weights
epoch 324



top10 acc train: 0.6880193948745728
top10 acc val: 0.3862016797065735
best score remains 0.3866208493709564; not saving weights
epoch 325



top10 acc train: 0.6882813572883606
top10 acc val: 0.38431552052497864
best score remains 0.3866208493709564; not saving weights
epoch 326



top10 acc train: 0.6897798180580139
top10 acc val: 0.38569870591163635
best score remains 0.3866208493709564; not saving weights
epoch 327



top10 acc train: 0.6906286478042603
top10 acc val: 0.38632744550704956
best score remains 0.3866208493709564; not saving weights
epoch 328



top10 acc train: 0.691791832447052
top10 acc val: 0.38796210289001465
new best score: 0.38796210289001465; saving weights @ models/last_run_weights.h5py
epoch 329



top10 acc train: 0.6915403008460999
top10 acc val: 0.3867884874343872
best score remains 0.38796210289001465; not saving weights
epoch 330



top10 acc train: 0.6906076669692993
top10 acc val: 0.38657891750335693
best score remains 0.38796210289001465; not saving weights
epoch 331



top10 acc train: 0.6852529048919678
top10 acc val: 0.3799144923686981
best score remains 0.38796210289001465; not saving weights
epoch 332



top10 acc train: 0.6620733737945557
top10 acc val: 0.3747170865535736
best score remains 0.38796210289001465; not saving weights
epoch 333



top10 acc train: 0.6500748991966248
top10 acc val: 0.367340087890625
best score remains 0.38796210289001465; not saving weights
epoch 334



top10 acc train: 0.6510809063911438
top10 acc val: 0.37530389428138733
best score remains 0.38796210289001465; not saving weights
epoch 335



top10 acc train: 0.6588877439498901
top10 acc val: 0.3772738575935364
best score remains 0.38796210289001465; not saving weights
epoch 336



top10 acc train: 0.6657934188842773
top10 acc val: 0.38502809405326843
best score remains 0.38796210289001465; not saving weights
epoch 337



top10 acc train: 0.6709176301956177
top10 acc val: 0.38506999611854553
best score remains 0.38796210289001465; not saving weights
epoch 338



top10 acc train: 0.6720913052558899
top10 acc val: 0.38645318150520325
best score remains 0.38796210289001465; not saving weights
epoch 339



top10 acc train: 0.6774565577507019
top10 acc val: 0.38511189818382263
best score remains 0.38796210289001465; not saving weights
epoch 340



top10 acc train: 0.6794475317001343
top10 acc val: 0.38636934757232666
best score remains 0.38796210289001465; not saving weights
epoch 341



top10 acc train: 0.6803487539291382
top10 acc val: 0.3883812427520752
new best score: 0.3883812427520752; saving weights @ models/last_run_weights.h5py
epoch 342



top10 acc train: 0.6830208897590637
top10 acc val: 0.3877106308937073
best score remains 0.3883812427520752; not saving weights
epoch 343



top10 acc train: 0.6836495995521545
top10 acc val: 0.38875848054885864
new best score: 0.38875848054885864; saving weights @ models/last_run_weights.h5py
epoch 344



top10 acc train: 0.6857768893241882
top10 acc val: 0.3882136046886444
best score remains 0.38875848054885864; not saving weights
epoch 345



top10 acc train: 0.6855568289756775
top10 acc val: 0.3873752951622009
best score remains 0.38875848054885864; not saving weights
epoch 346



top10 acc train: 0.6867304444313049
top10 acc val: 0.3875429630279541
best score remains 0.38875848054885864; not saving weights
epoch 347



top10 acc train: 0.6888052821159363
top10 acc val: 0.38951295614242554
new best score: 0.38951295614242554; saving weights @ models/last_run_weights.h5py
epoch 348



top10 acc train: 0.689025342464447
top10 acc val: 0.3891776204109192
best score remains 0.38951295614242554; not saving weights
epoch 349



top10 acc train: 0.6899265646934509
top10 acc val: 0.38880041241645813
best score remains 0.38951295614242554; not saving weights
epoch 350



top10 acc train: 0.6909849047660828
top10 acc val: 0.3889261484146118
best score remains 0.38951295614242554; not saving weights
epoch 351



top10 acc train: 0.6913831233978271
top10 acc val: 0.3884231746196747
best score remains 0.38951295614242554; not saving weights
epoch 352



top10 acc train: 0.6926196217536926
top10 acc val: 0.38880041241645813
best score remains 0.38951295614242554; not saving weights
epoch 353



top10 acc train: 0.6938666701316833
top10 acc val: 0.38880041241645813
best score remains 0.38951295614242554; not saving weights
epoch 354



top10 acc train: 0.6949878931045532
top10 acc val: 0.3888842463493347
best score remains 0.38951295614242554; not saving weights
epoch 355



top10 acc train: 0.696067214012146
top10 acc val: 0.3898482620716095
new best score: 0.3898482620716095; saving weights @ models/last_run_weights.h5py
epoch 356



top10 acc train: 0.697010338306427
top10 acc val: 0.39030933380126953
new best score: 0.39030933380126953; saving weights @ models/last_run_weights.h5py
epoch 357



top10 acc train: 0.6969893574714661
top10 acc val: 0.39022549986839294
best score remains 0.39030933380126953; not saving weights
epoch 358



top10 acc train: 0.6979848742485046
top10 acc val: 0.39026740193367004
best score remains 0.39030933380126953; not saving weights
epoch 359



top10 acc train: 0.6983621120452881
top10 acc val: 0.390686571598053
new best score: 0.390686571598053; saving weights @ models/last_run_weights.h5py
epoch 360



top10 acc train: 0.6995881795883179
top10 acc val: 0.3906027376651764
best score remains 0.390686571598053; not saving weights
epoch 361



top10 acc train: 0.6999444365501404
top10 acc val: 0.3897225260734558
best score remains 0.390686571598053; not saving weights
epoch 362



top10 acc train: 0.699996829032898
top10 acc val: 0.3911895453929901
new best score: 0.3911895453929901; saving weights @ models/last_run_weights.h5py
epoch 363



top10 acc train: 0.7004684209823608
top10 acc val: 0.38854891061782837
best score remains 0.3911895453929901; not saving weights
epoch 364



top10 acc train: 0.7025956511497498
top10 acc val: 0.39181825518608093
new best score: 0.39181825518608093; saving weights @ models/last_run_weights.h5py
epoch 365



top10 acc train: 0.7032663226127625
top10 acc val: 0.39077040553092957
best score remains 0.39181825518608093; not saving weights
epoch 366



top10 acc train: 0.7038950324058533
top10 acc val: 0.391482949256897
best score remains 0.39181825518608093; not saving weights
epoch 367



top10 acc train: 0.7035177946090698
top10 acc val: 0.3899739980697632
best score remains 0.39181825518608093; not saving weights
epoch 368



top10 acc train: 0.7047228813171387
top10 acc val: 0.39315953850746155
new best score: 0.39315953850746155; saving weights @ models/last_run_weights.h5py
epoch 369



top10 acc train: 0.7043561339378357
top10 acc val: 0.3906027376651764
best score remains 0.39315953850746155; not saving weights
epoch 370



top10 acc train: 0.7033606171607971
top10 acc val: 0.3915248513221741
best score remains 0.39315953850746155; not saving weights
epoch 371



top10 acc train: 0.7033711075782776
top10 acc val: 0.3882136046886444
best score remains 0.39315953850746155; not saving weights
epoch 372



top10 acc train: 0.6792903542518616
top10 acc val: 0.3777768611907959
best score remains 0.39315953850746155; not saving weights
epoch 373



top10 acc train: 0.6700583696365356
top10 acc val: 0.37957918643951416
best score remains 0.39315953850746155; not saving weights
epoch 374



top10 acc train: 0.6710643768310547
top10 acc val: 0.3823036253452301
best score remains 0.39315953850746155; not saving weights
epoch 375



top10 acc train: 0.6758427619934082
top10 acc val: 0.384650856256485
best score remains 0.39315953850746155; not saving weights
epoch 376



top10 acc train: 0.6793532371520996
top10 acc val: 0.38724955916404724
best score remains 0.39315953850746155; not saving weights
epoch 377



top10 acc train: 0.6834924221038818
top10 acc val: 0.3875848650932312
best score remains 0.39315953850746155; not saving weights
epoch 378



top10 acc train: 0.6879460215568542
top10 acc val: 0.39026740193367004
best score remains 0.39315953850746155; not saving weights
epoch 379



top10 acc train: 0.6895493268966675
top10 acc val: 0.3929499685764313
best score remains 0.39315953850746155; not saving weights
epoch 380



top10 acc train: 0.6924310326576233
top10 acc val: 0.39160868525505066
best score remains 0.39315953850746155; not saving weights
epoch 381



top10 acc train: 0.694778323173523
top10 acc val: 0.39232122898101807
best score remains 0.39315953850746155; not saving weights
epoch 382



top10 acc train: 0.6959834098815918
top10 acc val: 0.3907284736633301
best score remains 0.39315953850746155; not saving weights
epoch 383



top10 acc train: 0.6971151232719421
top10 acc val: 0.3913152813911438
best score remains 0.39315953850746155; not saving weights
epoch 384



top10 acc train: 0.6971465945243835
top10 acc val: 0.39102187752723694
best score remains 0.39315953850746155; not saving weights
epoch 385



top10 acc train: 0.6998292207717896
top10 acc val: 0.3920278251171112
best score remains 0.39315953850746155; not saving weights
epoch 386



top10 acc train: 0.7002692818641663
top10 acc val: 0.39315953850746155
best score remains 0.39315953850746155; not saving weights
epoch 387



top10 acc train: 0.7008142471313477
top10 acc val: 0.3919859230518341
best score remains 0.39315953850746155; not saving weights
epoch 388



top10 acc train: 0.7013171911239624
top10 acc val: 0.3927403688430786
best score remains 0.39315953850746155; not saving weights
epoch 389



top10 acc train: 0.7021031379699707
top10 acc val: 0.39253079891204834
best score remains 0.39315953850746155; not saving weights
epoch 390



top10 acc train: 0.7031615376472473
top10 acc val: 0.39018359780311584
best score remains 0.39315953850746155; not saving weights
epoch 391



top10 acc train: 0.7040836811065674
top10 acc val: 0.3919439911842346
best score remains 0.39315953850746155; not saving weights
epoch 392



top10 acc train: 0.7049219608306885
top10 acc val: 0.391482949256897
best score remains 0.39315953850746155; not saving weights
epoch 393



top10 acc train: 0.7044504284858704
top10 acc val: 0.391482949256897
best score remains 0.39315953850746155; not saving weights
epoch 394



top10 acc train: 0.7051734924316406
top10 acc val: 0.3911057114601135
best score remains 0.39315953850746155; not saving weights
epoch 395



top10 acc train: 0.7058022022247314
top10 acc val: 0.3929080367088318
best score remains 0.39315953850746155; not saving weights
epoch 396



top10 acc train: 0.7071749567985535
top10 acc val: 0.3927403688430786
best score remains 0.39315953850746155; not saving weights
epoch 397



top10 acc train: 0.7068396210670471
top10 acc val: 0.390686571598053
best score remains 0.39315953850746155; not saving weights
epoch 398



top10 acc train: 0.7075731754302979
top10 acc val: 0.3906446397304535
best score remains 0.39315953850746155; not saving weights
epoch 399



top10 acc train: 0.7080971002578735
top10 acc val: 0.3929080367088318
best score remains 0.39315953850746155; not saving weights
epoch 400



top10 acc train: 0.7085896134376526
top10 acc val: 0.39311760663986206
best score remains 0.39315953850746155; not saving weights
epoch 401



top10 acc train: 0.7098785638809204
top10 acc val: 0.3918601870536804
best score remains 0.39315953850746155; not saving weights
epoch 402



top10 acc train: 0.7100252509117126
top10 acc val: 0.3933691084384918
new best score: 0.3933691084384918; saving weights @ models/last_run_weights.h5py
epoch 403



top10 acc train: 0.7127812504768372
top10 acc val: 0.3942073881626129
new best score: 0.3942073881626129; saving weights @ models/last_run_weights.h5py
epoch 404



top10 acc train: 0.7120791077613831
top10 acc val: 0.39240506291389465
best score remains 0.3942073881626129; not saving weights
epoch 405



top10 acc train: 0.7133994698524475
top10 acc val: 0.39391398429870605
best score remains 0.3942073881626129; not saving weights
epoch 406



top10 acc train: 0.713902473449707
top10 acc val: 0.39387208223342896
best score remains 0.3942073881626129; not saving weights
epoch 407



top10 acc train: 0.7150341868400574
top10 acc val: 0.3948361277580261
new best score: 0.3948361277580261; saving weights @ models/last_run_weights.h5py
epoch 408



top10 acc train: 0.7161030769348145
top10 acc val: 0.3921535611152649
best score remains 0.3948361277580261; not saving weights
epoch 409



top10 acc train: 0.7163231372833252
top10 acc val: 0.3945007920265198
best score remains 0.3948361277580261; not saving weights
epoch 410



top10 acc train: 0.7169099450111389
top10 acc val: 0.3951295018196106
new best score: 0.3951295018196106; saving weights @ models/last_run_weights.h5py
epoch 411



top10 acc train: 0.7187647223472595
top10 acc val: 0.39626121520996094
new best score: 0.39626121520996094; saving weights @ models/last_run_weights.h5py
epoch 412



top10 acc train: 0.7184608578681946
top10 acc val: 0.395925909280777
best score remains 0.39626121520996094; not saving weights
epoch 413



top10 acc train: 0.719634473323822
top10 acc val: 0.3971833288669586
new best score: 0.3971833288669586; saving weights @ models/last_run_weights.h5py
epoch 414



top10 acc train: 0.7208710312843323
top10 acc val: 0.39680609107017517
best score remains 0.3971833288669586; not saving weights
epoch 415



top10 acc train: 0.7212796807289124
top10 acc val: 0.3963450491428375
best score remains 0.3971833288669586; not saving weights
epoch 416



top10 acc train: 0.7220341563224792
top10 acc val: 0.39626121520996094
best score remains 0.3971833288669586; not saving weights
epoch 417



top10 acc train: 0.7218036651611328
top10 acc val: 0.3960097134113312
best score remains 0.3971833288669586; not saving weights
epoch 418



top10 acc train: 0.7176539897918701
top10 acc val: 0.3936625123023987
best score remains 0.3971833288669586; not saving weights
epoch 419



top10 acc train: 0.6796780824661255
top10 acc val: 0.37823790311813354
best score remains 0.3971833288669586; not saving weights
epoch 420



top10 acc train: 0.6732335090637207
top10 acc val: 0.3838125467300415
best score remains 0.3971833288669586; not saving weights
epoch 421



top10 acc train: 0.6791017651557922
top10 acc val: 0.3869561553001404
best score remains 0.3971833288669586; not saving weights
epoch 422



top10 acc train: 0.688595712184906
top10 acc val: 0.39240506291389465
best score remains 0.3971833288669586; not saving weights
epoch 423



top10 acc train: 0.6946840286254883
top10 acc val: 0.3943331241607666
best score remains 0.3971833288669586; not saving weights
epoch 424



top10 acc train: 0.6940657496452332
top10 acc val: 0.3956325054168701
best score remains 0.3971833288669586; not saving weights
epoch 425



top10 acc train: 0.69840407371521
top10 acc val: 0.3979378044605255
new best score: 0.3979378044605255; saving weights @ models/last_run_weights.h5py
epoch 426



top10 acc train: 0.698016345500946
top10 acc val: 0.3963450491428375
best score remains 0.3979378044605255; not saving weights
epoch 427



top10 acc train: 0.7012333869934082
top10 acc val: 0.39546483755111694
best score remains 0.3979378044605255; not saving weights
epoch 428



top10 acc train: 0.7013171911239624
top10 acc val: 0.39848268032073975
new best score: 0.39848268032073975; saving weights @ models/last_run_weights.h5py
epoch 429



top10 acc train: 0.7040417194366455
top10 acc val: 0.39768630266189575
best score remains 0.39848268032073975; not saving weights
epoch 430



top10 acc train: 0.7060222625732422
top10 acc val: 0.39927905797958374
new best score: 0.39927905797958374; saving weights @ models/last_run_weights.h5py
epoch 431



top10 acc train: 0.707248330116272
top10 acc val: 0.3973090648651123
best score remains 0.39927905797958374; not saving weights
epoch 432



top10 acc train: 0.7080132961273193
top10 acc val: 0.3965546190738678
best score remains 0.39927905797958374; not saving weights
epoch 433



top10 acc train: 0.7078770399093628
top10 acc val: 0.3959678113460541
best score remains 0.39927905797958374; not saving weights
epoch 434



top10 acc train: 0.7103710770606995
top10 acc val: 0.3978120684623718
best score remains 0.39927905797958374; not saving weights
epoch 435



top10 acc train: 0.7119324207305908
top10 acc val: 0.3972252607345581
best score remains 0.39927905797958374; not saving weights
epoch 436



top10 acc train: 0.7123620510101318
top10 acc val: 0.3974348306655884
best score remains 0.39927905797958374; not saving weights
epoch 437



top10 acc train: 0.7129069566726685
top10 acc val: 0.39777013659477234
best score remains 0.39927905797958374; not saving weights
epoch 438



top10 acc train: 0.7136090993881226
top10 acc val: 0.39684802293777466
best score remains 0.39927905797958374; not saving weights
epoch 439



top10 acc train: 0.7141854166984558
top10 acc val: 0.39672228693962097
best score remains 0.39927905797958374; not saving weights
epoch 440



top10 acc train: 0.715275228023529
top10 acc val: 0.39621928334236145
best score remains 0.39927905797958374; not saving weights
epoch 441



top10 acc train: 0.7168994545936584
top10 acc val: 0.39756056666374207
best score remains 0.39927905797958374; not saving weights
epoch 442



top10 acc train: 0.7163440585136414
top10 acc val: 0.39835694432258606
best score remains 0.39927905797958374; not saving weights
epoch 443



top10 acc train: 0.7178844809532166
top10 acc val: 0.39852461218833923
best score remains 0.39927905797958374; not saving weights
epoch 444



top10 acc train: 0.7178530693054199
top10 acc val: 0.39915332198143005
best score remains 0.39927905797958374; not saving weights
epoch 445



top10 acc train: 0.7187333106994629
top10 acc val: 0.3988599181175232
best score remains 0.39927905797958374; not saving weights
epoch 446



top10 acc train: 0.7192153334617615
top10 acc val: 0.3974348306655884
best score remains 0.39927905797958374; not saving weights
epoch 447



top10 acc train: 0.7203365564346313
top10 acc val: 0.3987341821193695
best score remains 0.39927905797958374; not saving weights
epoch 448



top10 acc train: 0.7199593186378479
top10 acc val: 0.3978539705276489
best score remains 0.39927905797958374; not saving weights
epoch 449



top10 acc train: 0.7214159369468689
top10 acc val: 0.39613547921180725
best score remains 0.39927905797958374; not saving weights
epoch 450



top10 acc train: 0.7212272882461548
top10 acc val: 0.39688992500305176
best score remains 0.39927905797958374; not saving weights
epoch 451



top10 acc train: 0.7143635749816895
top10 acc val: 0.39831504225730896
best score remains 0.39927905797958374; not saving weights
epoch 452



top10 acc train: 0.7078351378440857
top10 acc val: 0.39605164527893066
best score remains 0.39927905797958374; not saving weights
epoch 453



top10 acc train: 0.7015582323074341
top10 acc val: 0.39701569080352783
best score remains 0.39927905797958374; not saving weights
epoch 454



top10 acc train: 0.6971675157546997
top10 acc val: 0.3926565647125244
best score remains 0.39927905797958374; not saving weights
epoch 455



top10 acc train: 0.7005208134651184
top10 acc val: 0.3936625123023987
best score remains 0.39927905797958374; not saving weights
epoch 456



top10 acc train: 0.7018201947212219
top10 acc val: 0.3943750560283661
best score remains 0.39927905797958374; not saving weights
epoch 457



top10 acc train: 0.7045552134513855
top10 acc val: 0.39764440059661865
best score remains 0.39927905797958374; not saving weights
epoch 458



top10 acc train: 0.7057183980941772
top10 acc val: 0.39764440059661865
best score remains 0.39927905797958374; not saving weights
epoch 459



top10 acc train: 0.7075521945953369
top10 acc val: 0.39630311727523804
best score remains 0.39927905797958374; not saving weights
epoch 460



top10 acc train: 0.7094698548316956
top10 acc val: 0.3965546190738678
best score remains 0.39927905797958374; not saving weights
epoch 461



top10 acc train: 0.7119848132133484
top10 acc val: 0.39844077825546265
best score remains 0.39927905797958374; not saving weights
epoch 462



top10 acc train: 0.7140596508979797
top10 acc val: 0.3972252607345581
best score remains 0.39927905797958374; not saving weights
epoch 463



top10 acc train: 0.7147722244262695
top10 acc val: 0.3973090648651123
best score remains 0.39927905797958374; not saving weights
epoch 464



top10 acc train: 0.7156000733375549
top10 acc val: 0.3982731103897095
best score remains 0.39927905797958374; not saving weights
epoch 465



top10 acc train: 0.7168890237808228
top10 acc val: 0.3971414268016815
best score remains 0.39927905797958374; not saving weights
epoch 466



top10 acc train: 0.7179264426231384
top10 acc val: 0.39701569080352783
best score remains 0.39927905797958374; not saving weights
epoch 467



top10 acc train: 0.7190581560134888
top10 acc val: 0.3974348306655884
best score remains 0.39927905797958374; not saving weights
epoch 468



top10 acc train: 0.720577597618103
top10 acc val: 0.39772823452949524
best score remains 0.39927905797958374; not saving weights
epoch 469



top10 acc train: 0.7206299901008606
top10 acc val: 0.39902758598327637
best score remains 0.39927905797958374; not saving weights
epoch 470



top10 acc train: 0.7224742770195007
top10 acc val: 0.39844077825546265
best score remains 0.39927905797958374; not saving weights
epoch 471



top10 acc train: 0.7231030464172363
top10 acc val: 0.4002431035041809
new best score: 0.4002431035041809; saving weights @ models/last_run_weights.h5py
epoch 472



top10 acc train: 0.723134458065033
top10 acc val: 0.39919522404670715
best score remains 0.4002431035041809; not saving weights
epoch 473



top10 acc train: 0.7238051295280457
top10 acc val: 0.39919522404670715
best score remains 0.4002431035041809; not saving weights
epoch 474



top10 acc train: 0.7250626087188721
top10 acc val: 0.3994467258453369
best score remains 0.4002431035041809; not saving weights
epoch 475



top10 acc train: 0.7254084348678589
top10 acc val: 0.3996982276439667
best score remains 0.4002431035041809; not saving weights
epoch 476



top10 acc train: 0.7264039516448975
top10 acc val: 0.40057840943336487
new best score: 0.40057840943336487; saving weights @ models/last_run_weights.h5py
epoch 477



top10 acc train: 0.7278081178665161
top10 acc val: 0.40087181329727173
new best score: 0.40087181329727173; saving weights @ models/last_run_weights.h5py
epoch 478



top10 acc train: 0.7276089787483215
top10 acc val: 0.3993209898471832
best score remains 0.40087181329727173; not saving weights
epoch 479



top10 acc train: 0.7280805706977844
top10 acc val: 0.39902758598327637
best score remains 0.40087181329727173; not saving weights
epoch 480



top10 acc train: 0.7292227745056152
top10 acc val: 0.3994467258453369
best score remains 0.40087181329727173; not saving weights
epoch 481



top10 acc train: 0.7301030158996582
top10 acc val: 0.4010814130306244
new best score: 0.4010814130306244; saving weights @ models/last_run_weights.h5py
epoch 482



top10 acc train: 0.7275461554527283
top10 acc val: 0.4019615948200226
new best score: 0.4019615948200226; saving weights @ models/last_run_weights.h5py
epoch 483



top10 acc train: 0.7158935070037842
top10 acc val: 0.39927905797958374
best score remains 0.4019615948200226; not saving weights
epoch 484



top10 acc train: 0.7036959528923035
top10 acc val: 0.3958001434803009
best score remains 0.4019615948200226; not saving weights
epoch 485



top10 acc train: 0.7047752737998962
top10 acc val: 0.39777013659477234
best score remains 0.4019615948200226; not saving weights
epoch 486



top10 acc train: 0.7091659903526306
top10 acc val: 0.4010394811630249
best score remains 0.4019615948200226; not saving weights
epoch 487



top10 acc train: 0.7082333564758301
top10 acc val: 0.4001173675060272
best score remains 0.4019615948200226; not saving weights
epoch 488



top10 acc train: 0.7114503979682922
top10 acc val: 0.40003353357315063
best score remains 0.4019615948200226; not saving weights
epoch 489



top10 acc train: 0.714290201663971
top10 acc val: 0.4012490510940552
best score remains 0.4019615948200226; not saving weights
epoch 490



top10 acc train: 0.7152542471885681
top10 acc val: 0.4001173675060272
best score remains 0.4019615948200226; not saving weights
epoch 491



top10 acc train: 0.7151704430580139
top10 acc val: 0.39613547921180725
best score remains 0.4019615948200226; not saving weights
epoch 492



top10 acc train: 0.7158306241035461
top10 acc val: 0.40372201800346375
new best score: 0.40372201800346375; saving weights @ models/last_run_weights.h5py
epoch 493



top10 acc train: 0.7203575372695923
top10 acc val: 0.40208736062049866
best score remains 0.40372201800346375; not saving weights
epoch 494



top10 acc train: 0.7198860049247742
top10 acc val: 0.4001592695713043
best score remains 0.40372201800346375; not saving weights
epoch 495



top10 acc train: 0.7206509709358215
top10 acc val: 0.400285005569458
best score remains 0.40372201800346375; not saving weights
epoch 496



top10 acc train: 0.7223066091537476
top10 acc val: 0.4002012014389038
best score remains 0.40372201800346375; not saving weights
epoch 497



top10 acc train: 0.7230611443519592
top10 acc val: 0.4002012014389038
best score remains 0.40372201800346375; not saving weights
epoch 498



top10 acc train: 0.7237422466278076
top10 acc val: 0.4010394811630249
best score remains 0.40372201800346375; not saving weights
epoch 499



top10 acc train: 0.7242557406425476
top10 acc val: 0.4009556472301483
best score remains 0.40372201800346375; not saving weights


In [12]:
# config = stmp.default_config(n_items)
# model = stmp.model(config=config)
model.load_weights(model_saver.location)

for metric in test_metrics.values():
    metric.reset_states()

preds, ys = [], []
for X, y in tqdm(list(utils.batchify(X_test, y_test, shuffle=True, batch_size=config["batch_size"]))):
    X = [sess[::-1] for sess in X]
    X, mask = utils.mask_length(X, maskoff_vals=config["maskoff"], maskon_vals=config["maskon"], justify="right")
    ys.extend(y)
    preds.extend(model.test_step(tf.constant(X), tf.constant(mask), tf.constant(y), test_metrics.values()).numpy())

# brute force verify acc
acc, acc5, acc10, acc20 = 0, 0, 0, 0
for y, pred in tqdm(list(zip(ys, preds))):
    argsorted_preds = (-pred).argsort()
    if y in argsorted_preds[:20]:
        acc20 += 1

        if y in argsorted_preds[:10]:
            acc10 += 1

            if y in argsorted_preds[:5]:
                acc5 += 1

                if y == argsorted_preds[0]:
                    acc += 1

print("brute force sanity check acc", acc/len(ys))
print("brute force sanity check top5 acc", acc5/len(ys))
print("brute force sanity check top10 acc", acc10/len(ys))
print("brute force sanity check top20 acc", acc20/len(ys))

for label, metric in test_metrics.items():
    print(label, metric.result())


brute force sanity check acc 0.0868572174367006
brute force sanity check top5 acc 0.2728399895588619
brute force sanity check top10 acc 0.37770817019055075
brute force sanity check top20 acc 0.48146697990080917
acc tf.Tensor(0.08731402, shape=(), dtype=float32)
top5 acc tf.Tensor(0.2950274, shape=(), dtype=float32)
top10 acc tf.Tensor(0.38540852, shape=(), dtype=float32)
top20 acc tf.Tensor(0.48172802, shape=(), dtype=float32)
mrr5 tf.Tensor(0.14712977, shape=(), dtype=float32)
mrr10 tf.Tensor(0.16132635, shape=(), dtype=float32)
mrr20 tf.Tensor(0.16877256, shape=(), dtype=float32)


In [201]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6).reshape(2, 3)
c = np.arange(12).reshape(4, 3)

print(a)
print(b)
print(c)
print(utils.trilinear_product(a, b, c))

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
tf.Tensor(
[[  9  24  39  54]
 [ 66 216 366 516]], shape=(2, 4), dtype=int64)


In [27]:
inputs = [[3, 1, 2, 3], [1, 2, 3]]
inputs = [np.array(sess) for sess in inputs]
padded_inputs, mask = utils.mask_length(inputs, justify="right")

X_embeddings = tf.nn.embedding_lookup(tf.constant([[0, 0], [1, 1], [2, 2], [3, 3]], dtype=tf.float32), padded_inputs)
X_s = X_embeddings[:, :-1]
ms = utils.masked_mean(X_s, mask[:, :-1, None])
mt = X_embeddings[:, -1]

print(ms)

tf.Tensor(
[[2 2]
 [1.5 1.5]], shape=(2, 2), dtype=float32)


In [26]:
sessions = [
    [[0], [1]],
    [[1], [2], [3]]
]
sessions = [np.array(sess) for sess in sessions]

utils.mask_length(sessions)

(array([[[0],
         [0],
         [0],
         [1]],
 
        [[0],
         [1],
         [2],
         [3]]]),
 array([[0, 0, 1, 1],
        [0, 1, 1, 1]], dtype=float32))

In [60]:
# config = TestModel.default_config(n_items=4, embedding_size=3, max_session_len=3)
# model = TestModel.model(config=config)

config = stmp.default_config(n_items=5, embedding_size=3, learning_rate=.00000001)
model = stmp.model(config=config)

sessions = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]], dtype=np.int32)
labels = np.array([1, 2, 3], dtype=np.int32)
sessions, mask = utils.mask_length(sessions, maskoff_vals=config["maskoff"], maskon_vals=config["maskon"], justify="right")
print("sessions", sessions)
print("mask", mask)

for i in range(3):
    print("epoch", i)
    print("pred", model.train_step(tf.constant(sessions), tf.constant(mask), tf.constant(labels), [])[1])
    print("embs", model.item_embs)

sessions [[0 1 1 1]
 [0 2 2 2]
 [0 3 3 3]]
mask [[0 1 1 1]
 [0 1 1 1]
 [0 1 1 1]]
epoch 0
hs_val tf.Tensor(
[[-5.15e-06 -8.15e-05 -2.67e-05]
 [-7.32e-05 -2.18e-05 -4.38e-05]
 [6.04e-05 0.000156 8.73e-05]], shape=(3, 3), dtype=float32)
ht_val tf.Tensor(
[[-0.000153 -7.05e-05 1.82e-05]
 [4.13e-05 -4.16e-06 1.97e-06]
 [-0.000113 4.56e-05 -0.000115]], shape=(3, 3), dtype=float32)
trilinear_product tf.Tensor(
[[0 -6.63e-12 -6.34e-12 1.21e-12 -6.94e-12]
 [0 5.07e-12 -4.98e-13 -2.3e-12 -1.3e-12]
 [0 1.14e-11 -1.23e-11 1.56e-11 1.9e-11]], shape=(3, 5), dtype=float32)
sigmoid_fc [<tf.Variable 'dense_128/kernel:0' shape=(5, 5) dtype=float32, numpy=
array([[0.644, 0.262, 0.288, 0.764, -0.392],
       [0.55, -0.509, 0.343, 0.74, -0.364],
       [-0.434, 0.0031, 0.53, -0.0639, -0.335],
       [-0.761, -0.632, 0.355, -0.165, -0.139],
       [0.298, -0.386, 0.0566, 0.221, 0.532]], dtype=float32)>, <tf.Variable 'dense_128/bias:0' shape=(5,) dtype=float32, numpy=array([0, 0, 0, 0, 0], dtype=float32)>]


In [52]:
preds = [[1, 2, 3, 4], [1, 2, 3], []]
preds = [np.array(sess, dtype=np.float32) for sess in preds]

padded_preds, mask = utils.mask_length(preds)
print(utils.masked_mean(padded_preds, mask, axis=1))

ValueError: could not broadcast input array from shape (0) into shape (4)

In [40]:
@tf.function()
def graph(a): # in tensorflow graph mode
    print(f"in eager mode: {tf.executing_eagerly()}")
    tf.print(a * 0)

def eager(a): # in tensorflow eager mode
    print(f"in eager mode: {tf.executing_eagerly()}")
    tf.print(a * 0)

graph(tf.constant(np.nan))
eager(tf.constant(np.nan))

# wow optimizations

in eager mode: False
0
in eager mode: True
nan


In [112]:
import os
os.mkdir("58_acc_76_top5_85_top50.tf_save")
model.save_weights("58_acc_76_top5_85_top50.tf_save/model")

AttributeError: 'NoneType' object has no attribute 'replace'

In [6]:
# record experiment scores
import datetime

with open("last_expr_name.txt", "r+") as last_expr_name:
    try:
        last_expr_name = int(last_expr_name.read())+1
    except:
        last_expr_name = 0
with open("last_expr_name.txt", "w") as expr_names:
    expr_names.write(str(last_expr_name))

experiment_name = f"expr{last_expr_name}_{datetime.date.today()}"

import os
expr_dir = Path("records")/experiment_name
(expr_dir/"model").mkdir(parents=True, exist_ok=True)

print("saving at", str(expr_dir/"model/model"))
# model.save_weights(str(expr_dir/"model/model"))

topn_labels = ["acc", "top5 acc", "top10 acc", "top20 acc", "top50 acc"]
train_accs = [train_accs_rec[label] for label in topn_labels]
test_accs = [test_accs_rec[label] for label in topn_labels]
for label, train_acc, test_acc in zip(topn_labels, train_accs, test_accs):
    kwargs = {
        "title": f"test {label}",
        "xlabel": "epoch",
        "ylabel": label
    }
    save_accs(expr_dir/"scores", [test_acc], kwargs)
    
    kwargs = {
        "title": f"train {label}",
        "xlabel": "epoch",
        "ylabel": label
    }
    save_accs(expr_dir/"scores", [train_acc], kwargs)
    
kwargs = {
    "title": f"test accs",
    "xlabel": "epoch",
    "ylabel": "acc",
    "legend": topn_labels
}
save_accs(expr_dir/"scores", test_accs, kwargs)


with open(expr_dir/"scores"/"raw_scores.pickle", "wb+") as raw_scores_handle:
    scores = {}
    for label in topn_labels:
        scores[f"train {label}"] = train_accs_rec[label]
        scores[f"test {label}"] = test_accs_rec[label]
    pickle.dump(scores, raw_scores_handle)
    


SyntaxError: invalid syntax (<ipython-input-6-08255273a46b>, line 55)