In [1]:
%load_ext autoreload
%autoreload 2

from pathlib import Path
import random
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, formatter=dict(float=lambda x: "%.3g" % x))
import tensorflow as tf
import pandas as pd
from src import utils
from src.features.load_dataset import import_stamp_yoochoose
from scipy.sparse import csr_matrix
import matplotlib.pyplot as plt
from tqdm import tqdm
from collections import Counter
import os
import shutil
import datetime

from tensorflow import keras
from tqdm.notebook import tqdm
from collections import defaultdict
import functools
import copy
from itertools import chain
from src.models import TestModel
from src.models import stmp
from src.metrics import MrrMetric

physical_devices = tf.config.experimental.list_physical_devices('GPU')
print(f"tensorflow version: {tf.__version__}")

tensorflow version: 2.2.0


In [2]:
train_data, val_data, test_data, idx2item, embedding_sizes = import_stamp_yoochoose(64)

X_train, y_train = train_data
X_val, y_val = val_data
X_test, y_test = test_data

num_x_train = len(X_train)
n_items, max_session_len = embedding_sizes
max_embedding_key = n_items

print(f"n_items: {n_items}")
print(f"max_session_len: {max_session_len}")

using last item in session as class
using last item in session as class
train_val_test_split @ 0.8 train, 0.2 val, 0 test
n_items: 17695
max_session_len: 146


In [8]:
# config = TestModel.default_config(n_items, max_session_len)
# model = TestModel.model(config=config)

config = stmp.default_config(n_items)
model = stmp.model(config=config)

train_metrics = {
#     "acc": tf.keras.metrics.SparseCategoricalAccuracy(),
#     "top5 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=5),
    "top10 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=10),
#     "top20 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=20),
#     "mrr5": MrrMetric(k=5),
#     "mrr10": MrrMetric(k=10),
#     "mrr20": MrrMetric(k=20)
}
val_metrics = {
#     "acc": tf.keras.metrics.SparseCategoricalAccuracy(),
#     "top5 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=5),
    "top10 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=10),
#     "top20 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=20),
#     "mrr5": MrrMetric(k=5),
#     "mrr10": MrrMetric(k=10),
#     "mrr20": MrrMetric(k=20)
}
test_metrics = {
    "acc": tf.keras.metrics.SparseCategoricalAccuracy(),
    "top5 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=5),
    "top10 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=10),
    "top20 acc": tf.keras.metrics.SparseTopKCategoricalAccuracy(k=20),
    "mrr5": MrrMetric(k=5),
    "mrr10": MrrMetric(k=10),
    "mrr20": MrrMetric(k=20)
}

train_metrics_rec = defaultdict(lambda: [])
val_metrics_rec = defaultdict(lambda: [])
test_metrics_rec = defaultdict(lambda: [])

current_time = datetime.datetime.now().strftime("%Y-%m-%d_%H:%M:%S")
print(f"starting experiment '{current_time}'")
expr_dir = Path("logs")/current_time
train_log_dir = expr_dir/"train"
val_log_dir = expr_dir/"val"
test_log_dir = expr_dir/"test"

os.makedirs(expr_dir)
for tensorboard_dir in [train_log_dir, val_log_dir, test_log_dir]:
    os.makedirs(tensorboard_dir, exist_ok=True)

train_summary_writer = tf.summary.create_file_writer(str(train_log_dir))
val_summary_writer = tf.summary.create_file_writer(str(val_log_dir))
model_saver = utils.TopModelSaver("models/last_run_weights.h5py")

print(f"batch_size: {config['batch_size']}")
for epoch in range(config["epochs"]):
    print(f"epoch {epoch}")
    # Reset the metrics at the start of the next epoch
    for metric in utils.flatten([train_metrics.values(), val_metrics.values(), test_metrics.values()]):
        metric.reset_states()

    for i, (X, y) in tqdm(list(enumerate(utils.batchify(X_train, y_train, shuffle=True, batch_size=config["batch_size"])))):
        X = [sess[::-1] for sess in X] # reversing sessions so most recent item is last
        X, mask = utils.mask_length(X, maskoff_vals=config["maskoff"], maskon_vals=config["maskon"], justify="right")
        preds, loss = model.train_step(tf.constant(X), tf.constant(mask), tf.constant(y), train_metrics.values()) 
        with train_summary_writer.as_default():
            tf.summary.scalar('loss', loss.numpy(), step=epoch*(int(num_x_train/config["batch_size"])+1)+i)

    for X, y in tqdm(list(utils.batchify(X_val, y_val, shuffle=True, batch_size=config["batch_size"]))):
        X = [sess[::-1] for sess in X]
        X, mask = utils.mask_length(X, maskoff_vals=config["maskoff"], maskon_vals=config["maskon"], justify="right")
        model.test_step(tf.constant(X), tf.constant(mask), tf.constant(y), val_metrics.values())

    with train_summary_writer.as_default():
        for label, metric in train_metrics.items():
            train_metrics_rec[label].append(metric.result())
            print(f"{label} train: {metric.result()}")
            tf.summary.scalar(label, metric.result(), step=epoch)
    with val_summary_writer.as_default():
        for label, metric in val_metrics.items():
            val_metrics_rec[label].append(metric.result())
            print(f"{label} val: {metric.result()}")
            tf.summary.scalar(label, metric.result(), step=epoch)

    model_saver.save_best(model, val_metrics["top10 acc"].result())

starting experiment '2020-07-07_11:23:18'
batch_size: 2048
epoch 0



top10 acc train: 0.05151473730802536
top10 acc val: 0.05038142204284668
new best score: 0.05038142204284668; saving weights @ models/last_run_weights.h5py
epoch 1



top10 acc train: 0.02234121784567833
top10 acc val: 0.01596948690712452
best score remains 0.05038142204284668; not saving weights
epoch 2



top10 acc train: 0.01626339927315712
top10 acc val: 0.016430547460913658
best score remains 0.05038142204284668; not saving weights
epoch 3



top10 acc train: 0.02301187254488468
top10 acc val: 0.026070918887853622
best score remains 0.05038142204284668; not saving weights
epoch 4



top10 acc train: 0.02627084031701088
top10 acc val: 0.021250734105706215
best score remains 0.05038142204284668; not saving weights
epoch 5



top10 acc train: 0.022844208404421806
top10 acc val: 0.02234051562845707
best score remains 0.05038142204284668; not saving weights
epoch 6



top10 acc train: 0.022728940472006798
top10 acc val: 0.023262636736035347
best score remains 0.05038142204284668; not saving weights
epoch 7



top10 acc train: 0.024321747943758965
top10 acc val: 0.02330455183982849
best score remains 0.05038142204284668; not saving weights
epoch 8



top10 acc train: 0.025746891275048256
top10 acc val: 0.024226674810051918
best score remains 0.05038142204284668; not saving weights
epoch 9



top10 acc train: 0.02675287425518036
top10 acc val: 0.02384944260120392
best score remains 0.05038142204284668; not saving weights
epoch 10



top10 acc train: 0.02938310243189335
top10 acc val: 0.02577751688659191
best score remains 0.05038142204284668; not saving weights
epoch 11



top10 acc train: 0.032422009855508804
top10 acc val: 0.028166653588414192
best score remains 0.05038142204284668; not saving weights
epoch 12



top10 acc train: 0.03634115308523178
top10 acc val: 0.03080727718770504
best score remains 0.05038142204284668; not saving weights
epoch 13



top10 acc train: 0.03984113782644272
top10 acc val: 0.03411853313446045
best score remains 0.05038142204284668; not saving weights
epoch 14



top10 acc train: 0.041612088680267334
top10 acc val: 0.036172352731227875
best score remains 0.05038142204284668; not saving weights
epoch 15



top10 acc train: 0.04558362811803818
top10 acc val: 0.03810042887926102
best score remains 0.05038142204284668; not saving weights
epoch 16



top10 acc train: 0.04835008084774017
top10 acc val: 0.037136390805244446
best score remains 0.05038142204284668; not saving weights
epoch 17



top10 acc train: 0.05164048820734024
top10 acc val: 0.039315953850746155
best score remains 0.05038142204284668; not saving weights
epoch 18



top10 acc train: 0.054522208869457245
top10 acc val: 0.04053147882223129
best score remains 0.05038142204284668; not saving weights
epoch 19



top10 acc train: 0.06017038971185684
top10 acc val: 0.044345710426568985
best score remains 0.05038142204284668; not saving weights
epoch 20



top10 acc train: 0.0645715668797493
top10 acc val: 0.043591249734163284
best score remains 0.05038142204284668; not saving weights
epoch 21



top10 acc train: 0.07071226090192795
top10 acc val: 0.046441446989774704
best score remains 0.05038142204284668; not saving weights
epoch 22



top10 acc train: 0.07885443419218063
top10 acc val: 0.05017184838652611
best score remains 0.05038142204284668; not saving weights
epoch 23



top10 acc train: 0.0872376337647438
top10 acc val: 0.05587224289774895
new best score: 0.05587224289774895; saving weights @ models/last_run_weights.h5py
epoch 24



top10 acc train: 0.10353247076272964
top10 acc val: 0.05855478346347809
new best score: 0.05855478346347809; saving weights @ models/last_run_weights.h5py
epoch 25



top10 acc train: 0.11459828913211823
top10 acc val: 0.06283007562160492
new best score: 0.06283007562160492; saving weights @ models/last_run_weights.h5py
epoch 26



top10 acc train: 0.12556979060173035
top10 acc val: 0.06874004751443863
new best score: 0.06874004751443863; saving weights @ models/last_run_weights.h5py
epoch 27



top10 acc train: 0.14136163890361786
top10 acc val: 0.07096152007579803
new best score: 0.07096152007579803; saving weights @ models/last_run_weights.h5py
epoch 28



top10 acc train: 0.15558163821697235
top10 acc val: 0.07750020921230316
new best score: 0.07750020921230316; saving weights @ models/last_run_weights.h5py
epoch 29



top10 acc train: 0.17477916181087494
top10 acc val: 0.083200603723526
new best score: 0.083200603723526; saving weights @ models/last_run_weights.h5py
epoch 30



top10 acc train: 0.18433599174022675
top10 acc val: 0.08412272483110428
new best score: 0.08412272483110428; saving weights @ models/last_run_weights.h5py
epoch 31



top10 acc train: 0.1978643834590912
top10 acc val: 0.09430798888206482
new best score: 0.09430798888206482; saving weights @ models/last_run_weights.h5py
epoch 32



top10 acc train: 0.216810405254364
top10 acc val: 0.09875094145536423
new best score: 0.09875094145536423; saving weights @ models/last_run_weights.h5py
epoch 33



top10 acc train: 0.2307579517364502
top10 acc val: 0.10725961625576019
new best score: 0.10725961625576019; saving weights @ models/last_run_weights.h5py
epoch 34



top10 acc train: 0.24605727195739746
top10 acc val: 0.11254086345434189
new best score: 0.11254086345434189; saving weights @ models/last_run_weights.h5py
epoch 35



top10 acc train: 0.257657527923584
top10 acc val: 0.12054656445980072
new best score: 0.12054656445980072; saving weights @ models/last_run_weights.h5py
epoch 36



top10 acc train: 0.26726675033569336
top10 acc val: 0.12322910875082016
new best score: 0.12322910875082016; saving weights @ models/last_run_weights.h5py
epoch 37



top10 acc train: 0.2748640477657318
top10 acc val: 0.12243272364139557
best score remains 0.12322910875082016; not saving weights
epoch 38



top10 acc train: 0.28815141320228577
top10 acc val: 0.13228267431259155
new best score: 0.13228267431259155; saving weights @ models/last_run_weights.h5py
epoch 39



top10 acc train: 0.2904358208179474
top10 acc val: 0.13295330107212067
new best score: 0.13295330107212067; saving weights @ models/last_run_weights.h5py
epoch 40



top10 acc train: 0.30596569180488586
top10 acc val: 0.1416296362876892
new best score: 0.1416296362876892; saving weights @ models/last_run_weights.h5py
epoch 41



top10 acc train: 0.31027254462242126
top10 acc val: 0.1415877342224121
best score remains 0.1416296362876892; not saving weights
epoch 42



top10 acc train: 0.3205210268497467
top10 acc val: 0.14959342777729034
new best score: 0.14959342777729034; saving weights @ models/last_run_weights.h5py
epoch 43



top10 acc train: 0.3283907473087311
top10 acc val: 0.1551261693239212
new best score: 0.1551261693239212; saving weights @ models/last_run_weights.h5py
epoch 44



top10 acc train: 0.33986523747444153
top10 acc val: 0.16149719059467316
new best score: 0.16149719059467316; saving weights @ models/last_run_weights.h5py
epoch 45



top10 acc train: 0.342044860124588
top10 acc val: 0.15948528051376343
best score remains 0.16149719059467316; not saving weights
epoch 46



top10 acc train: 0.3499041199684143
top10 acc val: 0.16585631668567657
new best score: 0.16585631668567657; saving weights @ models/last_run_weights.h5py
epoch 47



top10 acc train: 0.3579205572605133
top10 acc val: 0.16824544966220856
new best score: 0.16824544966220856; saving weights @ models/last_run_weights.h5py
epoch 48



top10 acc train: 0.36430224776268005
top10 acc val: 0.17817923426628113
new best score: 0.17817923426628113; saving weights @ models/last_run_weights.h5py
epoch 49



top10 acc train: 0.37488603591918945
top10 acc val: 0.17629306018352509
best score remains 0.17817923426628113; not saving weights
epoch 50



top10 acc train: 0.37745338678359985
top10 acc val: 0.17872412502765656
new best score: 0.17872412502765656; saving weights @ models/last_run_weights.h5py
epoch 51



top10 acc train: 0.3790462017059326
top10 acc val: 0.18341855704784393
new best score: 0.18341855704784393; saving weights @ models/last_run_weights.h5py
epoch 52



top10 acc train: 0.3874608278274536
top10 acc val: 0.18459217250347137
new best score: 0.18459217250347137; saving weights @ models/last_run_weights.h5py
epoch 53



top10 acc train: 0.38946232199668884
top10 acc val: 0.18781960010528564
new best score: 0.18781960010528564; saving weights @ models/last_run_weights.h5py
epoch 54



top10 acc train: 0.3888440728187561
top10 acc val: 0.1889093816280365
new best score: 0.1889093816280365; saving weights @ models/last_run_weights.h5py
epoch 55



top10 acc train: 0.3934338688850403
top10 acc val: 0.18983151018619537
new best score: 0.18983151018619537; saving weights @ models/last_run_weights.h5py
epoch 56



top10 acc train: 0.39628416299819946
top10 acc val: 0.19762763381004333
new best score: 0.19762763381004333; saving weights @ models/last_run_weights.h5py
epoch 57



top10 acc train: 0.4009053707122803
top10 acc val: 0.19804677367210388
new best score: 0.19804677367210388; saving weights @ models/last_run_weights.h5py
epoch 58



top10 acc train: 0.4038499891757965
top10 acc val: 0.1979210376739502
best score remains 0.19804677367210388; not saving weights
epoch 59



top10 acc train: 0.40612393617630005
top10 acc val: 0.1933104246854782
best score remains 0.19804677367210388; not saving weights
epoch 60



top10 acc train: 0.39882007241249084
top10 acc val: 0.19020873308181763
best score remains 0.19804677367210388; not saving weights
epoch 61



top10 acc train: 0.4044158458709717
top10 acc val: 0.19586721062660217
best score remains 0.19804677367210388; not saving weights
epoch 62



top10 acc train: 0.4103260040283203
top10 acc val: 0.19754379987716675
best score remains 0.19804677367210388; not saving weights
epoch 63



top10 acc train: 0.4155759811401367
top10 acc val: 0.19758571684360504
best score remains 0.19804677367210388; not saving weights
epoch 64



top10 acc train: 0.41261041164398193
top10 acc val: 0.20274122059345245
new best score: 0.20274122059345245; saving weights @ models/last_run_weights.h5py
epoch 65



top10 acc train: 0.41134247183799744
top10 acc val: 0.19729231297969818
best score remains 0.20274122059345245; not saving weights
epoch 66



top10 acc train: 0.40666884183883667
top10 acc val: 0.19138234853744507
best score remains 0.20274122059345245; not saving weights
epoch 67



top10 acc train: 0.406941294670105
top10 acc val: 0.19310083985328674
best score remains 0.20274122059345245; not saving weights
epoch 68



top10 acc train: 0.40797871351242065
top10 acc val: 0.19427445530891418
best score remains 0.20274122059345245; not saving weights
epoch 69



top10 acc train: 0.40522274374961853
top10 acc val: 0.1896638423204422
best score remains 0.20274122059345245; not saving weights
epoch 70



top10 acc train: 0.4046778380870819
top10 acc val: 0.19087937474250793
best score remains 0.20274122059345245; not saving weights
epoch 71



top10 acc train: 0.4061448872089386
top10 acc val: 0.19016681611537933
best score remains 0.20274122059345245; not saving weights
epoch 72



top10 acc train: 0.4038499891757965
top10 acc val: 0.19025065004825592
best score remains 0.20274122059345245; not saving weights
epoch 73



top10 acc train: 0.4031793177127838
top10 acc val: 0.19385531544685364
best score remains 0.20274122059345245; not saving weights
epoch 74



top10 acc train: 0.4103260040283203
top10 acc val: 0.19519658386707306
best score remains 0.20274122059345245; not saving weights
epoch 75



top10 acc train: 0.40726613998413086
top10 acc val: 0.19280745089054108
best score remains 0.20274122059345245; not saving weights
epoch 76



top10 acc train: 0.4031059741973877
top10 acc val: 0.1941068023443222
best score remains 0.20274122059345245; not saving weights
epoch 77



top10 acc train: 0.4032212495803833
top10 acc val: 0.1926397830247879
best score remains 0.20274122059345245; not saving weights
epoch 78



top10 acc train: 0.40300118923187256
top10 acc val: 0.19372956454753876
best score remains 0.20274122059345245; not saving weights
epoch 79



top10 acc train: 0.40261346101760864
top10 acc val: 0.19398105144500732
best score remains 0.20274122059345245; not saving weights
epoch 80



top10 acc train: 0.4068469703197479
top10 acc val: 0.2016514390707016
best score remains 0.20274122059345245; not saving weights
epoch 81



top10 acc train: 0.4153035283088684
top10 acc val: 0.20408248901367188
new best score: 0.20408248901367188; saving weights @ models/last_run_weights.h5py
epoch 82



top10 acc train: 0.4182376563549042
top10 acc val: 0.2068488597869873
new best score: 0.2068488597869873; saving weights @ models/last_run_weights.h5py
epoch 83



top10 acc train: 0.42228254675865173
top10 acc val: 0.20730991661548615
new best score: 0.20730991661548615; saving weights @ models/last_run_weights.h5py
epoch 84



top10 acc train: 0.4261702299118042
top10 acc val: 0.20441780984401703
best score remains 0.20730991661548615; not saving weights
epoch 85



top10 acc train: 0.4340713918209076
top10 acc val: 0.2107049971818924
new best score: 0.2107049971818924; saving weights @ models/last_run_weights.h5py
epoch 86



top10 acc train: 0.436240553855896
top10 acc val: 0.2174113541841507
new best score: 0.2174113541841507; saving weights @ models/last_run_weights.h5py
epoch 87



top10 acc train: 0.4383677840232849
top10 acc val: 0.21166904270648956
best score remains 0.2174113541841507; not saving weights
epoch 88



top10 acc train: 0.4360414445400238
top10 acc val: 0.211417555809021
best score remains 0.2174113541841507; not saving weights
epoch 89



top10 acc train: 0.4394052028656006
top10 acc val: 0.21548327803611755
best score remains 0.2174113541841507; not saving weights
epoch 90



top10 acc train: 0.43637678027153015
top10 acc val: 0.21200436353683472
best score remains 0.2174113541841507; not saving weights
epoch 91



top10 acc train: 0.4418153762817383
top10 acc val: 0.2181238979101181
new best score: 0.2181238979101181; saving weights @ models/last_run_weights.h5py
epoch 92



top10 acc train: 0.44215071201324463
top10 acc val: 0.21929751336574554
new best score: 0.21929751336574554; saving weights @ models/last_run_weights.h5py
epoch 93



top10 acc train: 0.43961480259895325
top10 acc val: 0.21833346784114838
best score remains 0.21929751336574554; not saving weights
epoch 94



top10 acc train: 0.43850401043891907
top10 acc val: 0.2143515795469284
best score remains 0.21929751336574554; not saving weights
epoch 95



top10 acc train: 0.43914324045181274
top10 acc val: 0.21699219942092896
best score remains 0.21929751336574554; not saving weights
epoch 96



top10 acc train: 0.4386507272720337
top10 acc val: 0.21418392658233643
best score remains 0.21929751336574554; not saving weights
epoch 97



top10 acc train: 0.43887078762054443
top10 acc val: 0.21271690726280212
best score remains 0.21929751336574554; not saving weights
epoch 98



top10 acc train: 0.4386402368545532
top10 acc val: 0.20894458889961243
best score remains 0.21929751336574554; not saving weights
epoch 99



top10 acc train: 0.43199655413627625
top10 acc val: 0.20953139662742615
best score remains 0.21929751336574554; not saving weights
epoch 100



top10 acc train: 0.4324052333831787
top10 acc val: 0.21397434175014496
best score remains 0.21929751336574554; not saving weights
epoch 101



top10 acc train: 0.43222710490226746
top10 acc val: 0.20957331359386444
best score remains 0.21929751336574554; not saving weights
epoch 102



top10 acc train: 0.4355279803276062
top10 acc val: 0.20856735110282898
best score remains 0.21929751336574554; not saving weights
epoch 103



top10 acc train: 0.43124207854270935
top10 acc val: 0.2046273797750473
best score remains 0.21929751336574554; not saving weights
epoch 104



top10 acc train: 0.4357165992259979
top10 acc val: 0.21254925429821014
best score remains 0.21929751336574554; not saving weights
epoch 105



top10 acc train: 0.43980342149734497
top10 acc val: 0.2137228548526764
best score remains 0.21929751336574554; not saving weights
epoch 106



top10 acc train: 0.44600698351860046
top10 acc val: 0.21804006397724152
best score remains 0.21929751336574554; not saving weights
epoch 107



top10 acc train: 0.45303839445114136
top10 acc val: 0.22399194538593292
new best score: 0.22399194538593292; saving weights @ models/last_run_weights.h5py
epoch 108



top10 acc train: 0.4558677077293396
top10 acc val: 0.2218542993068695
best score remains 0.22399194538593292; not saving weights
epoch 109



top10 acc train: 0.455385684967041
top10 acc val: 0.22390812635421753
best score remains 0.22399194538593292; not saving weights
epoch 110



top10 acc train: 0.4560563266277313
top10 acc val: 0.22457875311374664
new best score: 0.22457875311374664; saving weights @ models/last_run_weights.h5py
epoch 111



top10 acc train: 0.45834076404571533
top10 acc val: 0.22617150843143463
new best score: 0.22617150843143463; saving weights @ models/last_run_weights.h5py
epoch 112



top10 acc train: 0.4606042206287384
top10 acc val: 0.22805766761302948
new best score: 0.22805766761302948; saving weights @ models/last_run_weights.h5py
epoch 113



top10 acc train: 0.46721646189689636
top10 acc val: 0.22986000776290894
new best score: 0.22986000776290894; saving weights @ models/last_run_weights.h5py
epoch 114



top10 acc train: 0.46583324670791626
top10 acc val: 0.2271774709224701
best score remains 0.22986000776290894; not saving weights
epoch 115



top10 acc train: 0.46528834104537964
top10 acc val: 0.22751277685165405
best score remains 0.22986000776290894; not saving weights
epoch 116



top10 acc train: 0.45987069606781006
top10 acc val: 0.22621342539787292
best score remains 0.22986000776290894; not saving weights
epoch 117



top10 acc train: 0.45951440930366516
top10 acc val: 0.22545896470546722
best score remains 0.22986000776290894; not saving weights
epoch 118



top10 acc train: 0.45509228110313416
top10 acc val: 0.21619582176208496
best score remains 0.22986000776290894; not saving weights
epoch 119



top10 acc train: 0.4522210359573364
top10 acc val: 0.21946516633033752
best score remains 0.22986000776290894; not saving weights
epoch 120



top10 acc train: 0.4512464702129364
top10 acc val: 0.21992622315883636
best score remains 0.22986000776290894; not saving weights
epoch 121



top10 acc train: 0.4465413987636566
top10 acc val: 0.21045351028442383
best score remains 0.22986000776290894; not saving weights
epoch 122



top10 acc train: 0.4375085234642029
top10 acc val: 0.212213933467865
best score remains 0.22986000776290894; not saving weights
epoch 123



top10 acc train: 0.43716269731521606
top10 acc val: 0.209824800491333
best score remains 0.22986000776290894; not saving weights
epoch 124



top10 acc train: 0.4417210817337036
top10 acc val: 0.21938133239746094
best score remains 0.22986000776290894; not saving weights
epoch 125



top10 acc train: 0.45055487751960754
top10 acc val: 0.21841730177402496
best score remains 0.22986000776290894; not saving weights
epoch 126



top10 acc train: 0.4454306364059448
top10 acc val: 0.21762092411518097
best score remains 0.22986000776290894; not saving weights
epoch 127



top10 acc train: 0.4473797380924225
top10 acc val: 0.21535752713680267
best score remains 0.22986000776290894; not saving weights
epoch 128



top10 acc train: 0.4443408250808716
top10 acc val: 0.2143096625804901
best score remains 0.22986000776290894; not saving weights
epoch 129



top10 acc train: 0.4428737461566925
top10 acc val: 0.21351328492164612
best score remains 0.22986000776290894; not saving weights
epoch 130



top10 acc train: 0.442884236574173
top10 acc val: 0.2144773304462433
best score remains 0.22986000776290894; not saving weights
epoch 131



top10 acc train: 0.45068061351776123
top10 acc val: 0.2212255895137787
best score remains 0.22986000776290894; not saving weights
epoch 132



top10 acc train: 0.4496327042579651
top10 acc val: 0.2189202755689621
best score remains 0.22986000776290894; not saving weights
epoch 133



top10 acc train: 0.45497700572013855
top10 acc val: 0.21707603335380554
best score remains 0.22986000776290894; not saving weights
epoch 134



top10 acc train: 0.45612969994544983
top10 acc val: 0.21728560328483582
best score remains 0.22986000776290894; not saving weights
epoch 135



top10 acc train: 0.45489317178726196
top10 acc val: 0.22239919006824493
best score remains 0.22986000776290894; not saving weights
epoch 136



top10 acc train: 0.4573557376861572
top10 acc val: 0.22231537103652954
best score remains 0.22986000776290894; not saving weights
epoch 137



top10 acc train: 0.45873895287513733
top10 acc val: 0.22311174869537354
best score remains 0.22986000776290894; not saving weights
epoch 138



top10 acc train: 0.45904284715652466
top10 acc val: 0.22286026179790497
best score remains 0.22986000776290894; not saving weights
epoch 139



top10 acc train: 0.45597249269485474
top10 acc val: 0.22432726621627808
best score remains 0.22986000776290894; not saving weights
epoch 140



top10 acc train: 0.4616835415363312
top10 acc val: 0.22726128995418549
best score remains 0.22986000776290894; not saving weights
epoch 141



top10 acc train: 0.46090811491012573
top10 acc val: 0.22164472937583923
best score remains 0.22986000776290894; not saving weights
epoch 142



top10 acc train: 0.45932579040527344
top10 acc val: 0.22235728800296783
best score remains 0.22986000776290894; not saving weights
epoch 143



top10 acc train: 0.4586656093597412
top10 acc val: 0.22290216386318207
best score remains 0.22986000776290894; not saving weights
epoch 144



top10 acc train: 0.46097099781036377
top10 acc val: 0.2189621925354004
best score remains 0.22986000776290894; not saving weights
epoch 145



top10 acc train: 0.46148446202278137
top10 acc val: 0.2264229953289032
best score remains 0.22986000776290894; not saving weights
epoch 146



top10 acc train: 0.46508923172950745
top10 acc val: 0.22910554707050323
best score remains 0.22986000776290894; not saving weights
epoch 147



top10 acc train: 0.47029727697372437
top10 acc val: 0.23279403150081635
new best score: 0.23279403150081635; saving weights @ models/last_run_weights.h5py
epoch 148



top10 acc train: 0.4694170653820038
top10 acc val: 0.22592002153396606
best score remains 0.23279403150081635; not saving weights
epoch 149



top10 acc train: 0.46643054485321045
top10 acc val: 0.22839298844337463
best score remains 0.23279403150081635; not saving weights
epoch 150



top10 acc train: 0.4706326127052307
top10 acc val: 0.22990192472934723
best score remains 0.23279403150081635; not saving weights
epoch 151



top10 acc train: 0.46872544288635254
top10 acc val: 0.2271774709224701
best score remains 0.23279403150081635; not saving weights
epoch 152



top10 acc train: 0.47353529930114746
top10 acc val: 0.22889596223831177
best score remains 0.23279403150081635; not saving weights
epoch 153



top10 acc train: 0.4708631634712219
top10 acc val: 0.23187190294265747
best score remains 0.23279403150081635; not saving weights
epoch 154



top10 acc train: 0.4732837975025177
top10 acc val: 0.23216530680656433
best score remains 0.23279403150081635; not saving weights
epoch 155



top10 acc train: 0.4717014729976654
top10 acc val: 0.2317042499780655
best score remains 0.23279403150081635; not saving weights
epoch 156



top10 acc train: 0.4731161296367645
top10 acc val: 0.2345544397830963
new best score: 0.2345544397830963; saving weights @ models/last_run_weights.h5py
epoch 157



top10 acc train: 0.4706326127052307
top10 acc val: 0.22533322870731354
best score remains 0.2345544397830963; not saving weights
epoch 158



top10 acc train: 0.46544551849365234
top10 acc val: 0.22386620938777924
best score remains 0.2345544397830963; not saving weights
epoch 159



top10 acc train: 0.46359074115753174
top10 acc val: 0.2248721569776535
best score remains 0.2345544397830963; not saving weights
epoch 160



top10 acc train: 0.46493205428123474
top10 acc val: 0.2233632355928421
best score remains 0.2345544397830963; not saving weights
epoch 161



top10 acc train: 0.4654559791088104
top10 acc val: 0.2286863923072815
best score remains 0.2345544397830963; not saving weights
epoch 162



top10 acc train: 0.46722695231437683
top10 acc val: 0.22914744913578033
best score remains 0.2345544397830963; not saving weights
epoch 163



top10 acc train: 0.4687463939189911
top10 acc val: 0.23191381990909576
best score remains 0.2345544397830963; not saving weights
epoch 164



top10 acc train: 0.47082123160362244
top10 acc val: 0.22512364387512207
best score remains 0.2345544397830963; not saving weights
epoch 165



top10 acc train: 0.46551886200904846
top10 acc val: 0.22692598402500153
best score remains 0.2345544397830963; not saving weights
epoch 166



top10 acc train: 0.46540358662605286
top10 acc val: 0.22428534924983978
best score remains 0.2345544397830963; not saving weights
epoch 167



top10 acc train: 0.4643871486186981
top10 acc val: 0.22759661078453064
best score remains 0.2345544397830963; not saving weights
epoch 168



top10 acc train: 0.4671221673488617
top10 acc val: 0.2279319316148758
best score remains 0.2345544397830963; not saving weights
epoch 169



top10 acc train: 0.47033920884132385
top10 acc val: 0.22889596223831177
best score remains 0.2345544397830963; not saving weights
epoch 170



top10 acc train: 0.47299039363861084
top10 acc val: 0.22822533547878265
best score remains 0.2345544397830963; not saving weights
epoch 171



top10 acc train: 0.47634366154670715
top10 acc val: 0.23359040915966034
best score remains 0.2345544397830963; not saving weights
epoch 172



top10 acc train: 0.4741849899291992
top10 acc val: 0.23522508144378662
new best score: 0.23522508144378662; saving weights @ models/last_run_weights.h5py
epoch 173



top10 acc train: 0.4805981516838074
top10 acc val: 0.23371616005897522
best score remains 0.23522508144378662; not saving weights
epoch 174



top10 acc train: 0.4735143482685089
top10 acc val: 0.23702740669250488
new best score: 0.23702740669250488; saving weights @ models/last_run_weights.h5py
epoch 175



top10 acc train: 0.4796340763568878
top10 acc val: 0.23266828060150146
best score remains 0.23702740669250488; not saving weights
epoch 176



top10 acc train: 0.4763332009315491
top10 acc val: 0.23065638542175293
best score remains 0.23702740669250488; not saving weights
epoch 177



top10 acc train: 0.47859665751457214
top10 acc val: 0.23367424309253693
best score remains 0.23702740669250488; not saving weights
epoch 178



top10 acc train: 0.47693049907684326
top10 acc val: 0.23216530680656433
best score remains 0.23702740669250488; not saving weights
epoch 179



top10 acc train: 0.47349339723587036
top10 acc val: 0.2324587106704712
best score remains 0.23702740669250488; not saving weights
epoch 180



top10 acc train: 0.47025537490844727
top10 acc val: 0.22914744913578033
best score remains 0.23702740669250488; not saving weights
epoch 181



top10 acc train: 0.47488710284233093
top10 acc val: 0.2316204160451889
best score remains 0.23702740669250488; not saving weights
epoch 182



top10 acc train: 0.4714709222316742
top10 acc val: 0.22818341851234436
best score remains 0.23702740669250488; not saving weights
epoch 183



top10 acc train: 0.4675622582435608
top10 acc val: 0.22826725244522095
best score remains 0.23702740669250488; not saving weights
epoch 184



top10 acc train: 0.4643557071685791
top10 acc val: 0.2248721569776535
best score remains 0.23702740669250488; not saving weights
epoch 185



top10 acc train: 0.45888566970825195
top10 acc val: 0.22068069875240326
best score remains 0.23702740669250488; not saving weights
epoch 186



top10 acc train: 0.45517608523368835
top10 acc val: 0.21975857019424438
best score remains 0.23702740669250488; not saving weights
epoch 187



top10 acc train: 0.4524725079536438
top10 acc val: 0.2204292118549347
best score remains 0.23702740669250488; not saving weights
epoch 188



top10 acc train: 0.45762819051742554
top10 acc val: 0.2240757793188095
best score remains 0.23702740669250488; not saving weights
epoch 189



top10 acc train: 0.45916858315467834
top10 acc val: 0.22830916941165924
best score remains 0.23702740669250488; not saving weights
epoch 190



top10 acc train: 0.46296200156211853
top10 acc val: 0.22592002153396606
best score remains 0.23702740669250488; not saving weights
epoch 191



top10 acc train: 0.46339163184165955
top10 acc val: 0.22436918318271637
best score remains 0.23702740669250488; not saving weights
epoch 192



top10 acc train: 0.4648796617984772
top10 acc val: 0.23141084611415863
best score remains 0.23702740669250488; not saving weights
epoch 193



top10 acc train: 0.46705928444862366
top10 acc val: 0.2293989509344101
best score remains 0.23702740669250488; not saving weights
epoch 194



top10 acc train: 0.4689035713672638
top10 acc val: 0.2309078723192215
best score remains 0.23702740669250488; not saving weights
epoch 195



top10 acc train: 0.4743002653121948
top10 acc val: 0.23639869689941406
best score remains 0.23702740669250488; not saving weights
epoch 196



top10 acc train: 0.4715547561645508
top10 acc val: 0.2271355539560318
best score remains 0.23702740669250488; not saving weights
epoch 197



top10 acc train: 0.4726445972919464
top10 acc val: 0.22688406705856323
best score remains 0.23702740669250488; not saving weights
epoch 198



top10 acc train: 0.4738287031650543
top10 acc val: 0.22612960636615753
best score remains 0.23702740669250488; not saving weights
epoch 199



top10 acc train: 0.4741849899291992
top10 acc val: 0.23254254460334778
best score remains 0.23702740669250488; not saving weights
epoch 200



top10 acc train: 0.47421643137931824
top10 acc val: 0.23442870378494263
best score remains 0.23702740669250488; not saving weights
epoch 201



top10 acc train: 0.4709155559539795
top10 acc val: 0.22960852086544037
best score remains 0.23702740669250488; not saving weights
epoch 202



top10 acc train: 0.47085267305374146
top10 acc val: 0.22897979617118835
best score remains 0.23702740669250488; not saving weights
epoch 203



top10 acc train: 0.4711041748523712
top10 acc val: 0.2279319316148758
best score remains 0.23702740669250488; not saving weights
epoch 204



top10 acc train: 0.4739963710308075
top10 acc val: 0.23296168446540833
best score remains 0.23702740669250488; not saving weights
epoch 205



top10 acc train: 0.4741849899291992
top10 acc val: 0.2332131713628769
best score remains 0.23702740669250488; not saving weights
epoch 206



top10 acc train: 0.47389158606529236
top10 acc val: 0.23178808391094208
best score remains 0.23702740669250488; not saving weights
epoch 207



top10 acc train: 0.47215208411216736
top10 acc val: 0.23354849219322205
best score remains 0.23702740669250488; not saving weights
epoch 208



top10 acc train: 0.47630175948143005
top10 acc val: 0.23585380613803864
best score remains 0.23702740669250488; not saving weights
epoch 209



top10 acc train: 0.47615504264831543
top10 acc val: 0.2330455183982849
best score remains 0.23702740669250488; not saving weights
epoch 210



top10 acc train: 0.4699934124946594
top10 acc val: 0.22822533547878265
best score remains 0.23702740669250488; not saving weights
epoch 211



top10 acc train: 0.4700038731098175
top10 acc val: 0.22734512388706207
best score remains 0.23702740669250488; not saving weights
epoch 212



top10 acc train: 0.4671535789966583
top10 acc val: 0.22353088855743408
best score remains 0.23702740669250488; not saving weights
epoch 213



top10 acc train: 0.46797093749046326
top10 acc val: 0.22374045848846436
best score remains 0.23702740669250488; not saving weights
epoch 214



top10 acc train: 0.4681490957736969
top10 acc val: 0.2309078723192215
best score remains 0.23702740669250488; not saving weights
epoch 215



top10 acc train: 0.47250837087631226
top10 acc val: 0.22990192472934723
best score remains 0.23702740669250488; not saving weights
epoch 216



top10 acc train: 0.4772658348083496
top10 acc val: 0.2353089153766632
best score remains 0.23702740669250488; not saving weights
epoch 217



top10 acc train: 0.4812583029270172
top10 acc val: 0.2338838130235672
best score remains 0.23702740669250488; not saving weights
epoch 218



top10 acc train: 0.4797598123550415
top10 acc val: 0.2353508323431015
best score remains 0.23702740669250488; not saving weights
epoch 219



top10 acc train: 0.4822014272212982
top10 acc val: 0.23438678681850433
best score remains 0.23702740669250488; not saving weights
epoch 220



top10 acc train: 0.4760397672653198
top10 acc val: 0.2270517200231552
best score remains 0.23702740669250488; not saving weights
epoch 221



top10 acc train: 0.4730846881866455
top10 acc val: 0.22684215009212494
best score remains 0.23702740669250488; not saving weights
epoch 222



top10 acc train: 0.4720996618270874
top10 acc val: 0.22520747780799866
best score remains 0.23702740669250488; not saving weights
epoch 223



top10 acc train: 0.47038111090660095
top10 acc val: 0.22843490540981293
best score remains 0.23702740669250488; not saving weights
epoch 224



top10 acc train: 0.46362218260765076
top10 acc val: 0.22650682926177979
best score remains 0.23702740669250488; not saving weights
epoch 225



top10 acc train: 0.4677089750766754
top10 acc val: 0.2286444753408432
best score remains 0.23702740669250488; not saving weights
epoch 226



top10 acc train: 0.4668077826499939
top10 acc val: 0.22675831615924835
best score remains 0.23702740669250488; not saving weights
epoch 227



top10 acc train: 0.46804431080818176
top10 acc val: 0.22747087478637695
best score remains 0.23702740669250488; not saving weights
epoch 228



top10 acc train: 0.46908172965049744
top10 acc val: 0.2286025583744049
best score remains 0.23702740669250488; not saving weights
epoch 229



top10 acc train: 0.4726864993572235
top10 acc val: 0.2286863923072815
best score remains 0.23702740669250488; not saving weights
epoch 230



top10 acc train: 0.472214937210083
top10 acc val: 0.22973425686359406
best score remains 0.23702740669250488; not saving weights
epoch 231



top10 acc train: 0.47294846177101135
top10 acc val: 0.23141084611415863
best score remains 0.23702740669250488; not saving weights
epoch 232



top10 acc train: 0.47946640849113464
top10 acc val: 0.23346467316150665
best score remains 0.23702740669250488; not saving weights
epoch 233



top10 acc train: 0.47926729917526245
top10 acc val: 0.23187190294265747
best score remains 0.23702740669250488; not saving weights
epoch 234



top10 acc train: 0.47848138213157654
top10 acc val: 0.22902171313762665
best score remains 0.23702740669250488; not saving weights
epoch 235



top10 acc train: 0.47634366154670715
top10 acc val: 0.23149468004703522
best score remains 0.23702740669250488; not saving weights
epoch 236



top10 acc train: 0.4799589216709137
top10 acc val: 0.23593762516975403
best score remains 0.23702740669250488; not saving weights
epoch 237



top10 acc train: 0.4785861670970917
top10 acc val: 0.23074021935462952
best score remains 0.23702740669250488; not saving weights
epoch 238



top10 acc train: 0.47440505027770996
top10 acc val: 0.2263391762971878
best score remains 0.23702740669250488; not saving weights
epoch 239



top10 acc train: 0.4722044765949249
top10 acc val: 0.22604577243328094
best score remains 0.23702740669250488; not saving weights
epoch 240



top10 acc train: 0.4722883105278015
top10 acc val: 0.2286025583744049
best score remains 0.23702740669250488; not saving weights
epoch 241



top10 acc train: 0.4703601598739624
top10 acc val: 0.22755469381809235
best score remains 0.23702740669250488; not saving weights
epoch 242



top10 acc train: 0.4698152542114258
top10 acc val: 0.22617150843143463
best score remains 0.23702740669250488; not saving weights
epoch 243



top10 acc train: 0.4710412919521332
top10 acc val: 0.22889596223831177
best score remains 0.23702740669250488; not saving weights
epoch 244



top10 acc train: 0.4736820161342621
top10 acc val: 0.2293151170015335
best score remains 0.23702740669250488; not saving weights
epoch 245



top10 acc train: 0.47424787282943726
top10 acc val: 0.22973425686359406
best score remains 0.23702740669250488; not saving weights
epoch 246



top10 acc train: 0.4785442650318146
top10 acc val: 0.23141084611415863
best score remains 0.23702740669250488; not saving weights
epoch 247



top10 acc train: 0.48206520080566406
top10 acc val: 0.23375806212425232
best score remains 0.23702740669250488; not saving weights
epoch 248



top10 acc train: 0.48377329111099243
top10 acc val: 0.23778188228607178
new best score: 0.23778188228607178; saving weights @ models/last_run_weights.h5py
epoch 249



top10 acc train: 0.4830397367477417
top10 acc val: 0.23514124751091003
best score remains 0.23778188228607178; not saving weights
epoch 250



top10 acc train: 0.48340651392936707
top10 acc val: 0.2369435876607895
best score remains 0.23778188228607178; not saving weights
epoch 251



top10 acc train: 0.48850977420806885
top10 acc val: 0.24004526436328888
new best score: 0.24004526436328888; saving weights @ models/last_run_weights.h5py
epoch 252



top10 acc train: 0.4882897138595581
top10 acc val: 0.23191381990909576
best score remains 0.24004526436328888; not saving weights
epoch 253



top10 acc train: 0.48025232553482056
top10 acc val: 0.23183000087738037
best score remains 0.24004526436328888; not saving weights
epoch 254



top10 acc train: 0.47828227281570435
top10 acc val: 0.2271774709224701
best score remains 0.24004526436328888; not saving weights
epoch 255



top10 acc train: 0.47645893692970276
top10 acc val: 0.23220722377300262
best score remains 0.24004526436328888; not saving weights
epoch 256



top10 acc train: 0.4772658348083496
top10 acc val: 0.23187190294265747
best score remains 0.24004526436328888; not saving weights
epoch 257



top10 acc train: 0.479801744222641
top10 acc val: 0.23111744225025177
best score remains 0.24004526436328888; not saving weights
epoch 258



top10 acc train: 0.47875383496284485
top10 acc val: 0.22772236168384552
best score remains 0.24004526436328888; not saving weights
epoch 259



top10 acc train: 0.4799484312534332
top10 acc val: 0.2331712692975998
best score remains 0.24004526436328888; not saving weights


In [14]:
model.load_weights(model_saver.location)

for metric in test_metrics.values():
    metric.reset_states()

preds, ys = [], []
for X, y in tqdm(list(utils.batchify(X_test, y_test, shuffle=True, batch_size=config["batch_size"]))):
    X = [sess[::-1] for sess in X]
    X, mask = utils.mask_length(X, maskoff_vals=config["maskoff"], maskon_vals=config["maskon"], justify="right")
    ys.extend(y)
    preds.extend(model.test_step(tf.constant(X), tf.constant(mask), tf.constant(y), test_metrics.values()).numpy())

# brute force verify acc
acc, acc5, acc10, acc20 = 0, 0, 0, 0
for y, pred in tqdm(list(zip(ys, preds))):
    argsorted_preds = (-pred).argsort()
    if y in argsorted_preds[:20]:
        acc20 += 1

        if y in argsorted_preds[:10]:
            acc10 += 1

            if y in argsorted_preds[:5]:
                acc5 += 1

                if y == argsorted_preds[0]:
                    acc += 1

print("brute force sanity check top20 acc", acc20/len(ys))
print("brute force sanity check top10 acc", acc10/len(ys))
print("brute force sanity check top5 acc", acc5/len(ys))
print("brute force sanity check acc", acc/len(ys))

for label, metric in test_metrics.items():
    print(label, metric.result())


brute force sanity check top20 acc 0.35010441138084053
brute force sanity check top10 acc 0.22500652571130253
brute force sanity check top5 acc 0.14056382145653876
brute force sanity check acc 0.0383059253458627
acc tf.Tensor(0.038240667, shape=(), dtype=float32)
top5 acc tf.Tensor(0.14402245, shape=(), dtype=float32)
top10 acc tf.Tensor(0.22820413, shape=(), dtype=float32)
top20 acc tf.Tensor(0.35297573, shape=(), dtype=float32)
mrr5 tf.Tensor(0.07290416, shape=(), dtype=float32)
mrr10 tf.Tensor(0.08403894, shape=(), dtype=float32)
mrr20 tf.Tensor(0.09257878, shape=(), dtype=float32)


In [201]:
a = np.arange(6).reshape(2, 3)
b = np.arange(6).reshape(2, 3)
c = np.arange(12).reshape(4, 3)

print(a)
print(b)
print(c)
print(utils.trilinear_product(a, b, c))

[[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
tf.Tensor(
[[  9  24  39  54]
 [ 66 216 366 516]], shape=(2, 4), dtype=int64)


In [27]:
inputs = [[3, 1, 2, 3], [1, 2, 3]]
inputs = [np.array(sess) for sess in inputs]
padded_inputs, mask = utils.mask_length(inputs, justify="right")

X_embeddings = tf.nn.embedding_lookup(tf.constant([[0, 0], [1, 1], [2, 2], [3, 3]], dtype=tf.float32), padded_inputs)
X_s = X_embeddings[:, :-1]
ms = utils.masked_mean(X_s, mask[:, :-1, None])
mt = X_embeddings[:, -1]

print(ms)

tf.Tensor(
[[2 2]
 [1.5 1.5]], shape=(2, 2), dtype=float32)


In [26]:
sessions = [
    [[0], [1]],
    [[1], [2], [3]]
]
sessions = [np.array(sess) for sess in sessions]

utils.mask_length(sessions)

(array([[[0],
         [0],
         [0],
         [1]],
 
        [[0],
         [1],
         [2],
         [3]]]),
 array([[0, 0, 1, 1],
        [0, 1, 1, 1]], dtype=float32))

In [75]:
# config = TestModel.default_config(n_items=4, embedding_size=3, max_session_len=3)
# model = TestModel.model(config=config)

config = stmp.default_config(n_items=4, embedding_size=3)
model = stmp.model(config=config)

sessions = np.array([[1, 2, 3]], dtype=np.int32)
labels = np.array([1], dtype=np.int32)
sessions, mask = utils.mask_length(sessions, maskoff_vals=config["maskoff"], maskon_vals=config["maskon"], justify="right")
print("sessions", sessions)
print("mask", mask)

for i in range(1000):
    print("epoch", i)
    print("pred", model.train_step(tf.constant(sessions), tf.constant(mask), tf.constant(labels), [])[1])
    print("embs", model.item_embs)

sessions [[0 1 2 3]]
mask [[0 1 1 1]]
epoch 0
pred tf.Tensor(1.3862951, shape=(), dtype=float32)
embs <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[1.67e-06, 2.54e-07, -7.72e-07],
       [0.000288, -0.00223, -0.00119],
       [0.000436, -0.00569, -0.00125],
       [-0.00156, -0.00288, 0.000633]], dtype=float32)>
epoch 1
pred tf.Tensor(1.3862956, shape=(), dtype=float32)
embs <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[2.26e-06, 3.46e-07, -8.79e-07],
       [0.000281, -0.00223, -0.00119],
       [0.000439, -0.00569, -0.00125],
       [-0.00156, -0.00287, 0.00063]], dtype=float32)>
epoch 2
pred tf.Tensor(1.3862926, shape=(), dtype=float32)
embs <tf.Variable 'Variable:0' shape=(4, 3) dtype=float32, numpy=
array([[2.61e-06, 4.02e-07, -7.42e-07],
       [0.000274, -0.00223, -0.00119],
       [0.000442, -0.00568, -0.00125],
       [-0.00156, -0.00287, 0.000627]], dtype=float32)>


In [52]:
preds = [[1, 2, 3, 4], [1, 2, 3], []]
preds = [np.array(sess, dtype=np.float32) for sess in preds]

padded_preds, mask = utils.mask_length(preds)
print(utils.masked_mean(padded_preds, mask, axis=1))

ValueError: could not broadcast input array from shape (0) into shape (4)

In [40]:
@tf.function()
def graph(a): # in tensorflow graph mode
    print(f"in eager mode: {tf.executing_eagerly()}")
    tf.print(a * 0)

def eager(a): # in tensorflow eager mode
    print(f"in eager mode: {tf.executing_eagerly()}")
    tf.print(a * 0)

graph(tf.constant(np.nan))
eager(tf.constant(np.nan))

# wow optimizations

in eager mode: False
0
in eager mode: True
nan


In [112]:
import os
os.mkdir("58_acc_76_top5_85_top50.tf_save")
model.save_weights("58_acc_76_top5_85_top50.tf_save/model")

AttributeError: 'NoneType' object has no attribute 'replace'

In [6]:
# record experiment scores
import datetime

with open("last_expr_name.txt", "r+") as last_expr_name:
    try:
        last_expr_name = int(last_expr_name.read())+1
    except:
        last_expr_name = 0
with open("last_expr_name.txt", "w") as expr_names:
    expr_names.write(str(last_expr_name))

experiment_name = f"expr{last_expr_name}_{datetime.date.today()}"

import os
expr_dir = Path("records")/experiment_name
(expr_dir/"model").mkdir(parents=True, exist_ok=True)

print("saving at", str(expr_dir/"model/model"))
# model.save_weights(str(expr_dir/"model/model"))

topn_labels = ["acc", "top5 acc", "top10 acc", "top20 acc", "top50 acc"]
train_accs = [train_accs_rec[label] for label in topn_labels]
test_accs = [test_accs_rec[label] for label in topn_labels]
for label, train_acc, test_acc in zip(topn_labels, train_accs, test_accs):
    kwargs = {
        "title": f"test {label}",
        "xlabel": "epoch",
        "ylabel": label
    }
    save_accs(expr_dir/"scores", [test_acc], kwargs)
    
    kwargs = {
        "title": f"train {label}",
        "xlabel": "epoch",
        "ylabel": label
    }
    save_accs(expr_dir/"scores", [train_acc], kwargs)
    
kwargs = {
    "title": f"test accs",
    "xlabel": "epoch",
    "ylabel": "acc",
    "legend": topn_labels
}
save_accs(expr_dir/"scores", test_accs, kwargs)


with open(expr_dir/"scores"/"raw_scores.pickle", "wb+") as raw_scores_handle:
    scores = {}
    for label in topn_labels:
        scores[f"train {label}"] = train_accs_rec[label]
        scores[f"test {label}"] = test_accs_rec[label]
    pickle.dump(scores, raw_scores_handle)
    


SyntaxError: invalid syntax (<ipython-input-6-08255273a46b>, line 55)